"""
Final mapping: combine TWSE (stock_info.xlsx) + OTC (TPEX API) to match all NBIM TW companies.
"""

import csv
import re
import json
import requests
import openpyxl
from collections import defaultdict

# ── Load TWSE stock_info.xlsx ──
wb = openpyxl.load_workbook('/home/tearicee/data_collector/nbim/stock_info.xlsx', read_only=True)
ws = wb['t187ap03_L']

stocks = {}  # code -> info
for row in ws.iter_rows(min_row=2, values_only=True):
    code = row[1]
    if code is None:
        continue
    code = str(code).strip()
    stocks[code] = {
        'code': code,
        'full_name': str(row[2] or ''),
        'short_name': str(row[3] or ''),
        'eng_abbrev': str(row[27] or ''),
        'market': 'TWSE',
    }
wb.close()
print(f"Loaded {len(stocks)} TWSE stocks")

# ── Load OTC from TPEX API ──
resp = requests.get('https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap03_O', timeout=30)
resp.raise_for_status()
otc_data = resp.json()
otc_count = 0
for item in otc_data:
    code = str(item.get('SecuritiesCompanyCode', '')).strip()
    if not code:
        continue
    if code not in stocks:  # Don't overwrite TWSE data
        stocks[code] = {
            'code': code,
            'full_name': item.get('CompanyName', ''),
            'short_name': item.get('CompanyAbbreviation', ''),
            'eng_abbrev': item.get('Symbol', ''),
            'market': 'OTC',
        }
        otc_count += 1
print(f"Loaded {otc_count} OTC stocks (total: {len(stocks)})")

# ── Load NBIM TW companies ──
company_tickers = defaultdict(set)
with open('/home/tearicee/data_collector/nbim/nbim_all_holdings.csv', encoding='utf-8-sig') as f:
    reader = csv.DictReader(f)
    for row in reader:
        if row['country_code'] == 'TW':
            name = row['company_name']
            ticker = row['ticker'].strip()
            if ticker:
                company_tickers[name].add(ticker)
            else:
                company_tickers[name]

all_names = sorted(company_tickers.keys())
print(f"Found {len(all_names)} unique TW companies in NBIM")

# ── Step 1: Match by ticker ──
mapping = {}

for name in all_names:
    tickers = company_tickers[name]
    if not tickers:
        continue
    for t in sorted(tickers):
        clean = t.replace(' ', '')
        if clean in stocks:
            s = stocks[clean]
            mapping[name] = {
                'code': s['code'],
                'short_name': s['short_name'],
                'eng_abbrev': s['eng_abbrev'],
                'full_name': s['full_name'],
                'market': s['market'],
                'match_method': 'ticker',
            }
            break
    if name not in mapping:
        # Try stripping leading zeros and trailing T
        for t in sorted(tickers):
            clean = re.sub(r'^0+', '', t.rstrip('T '))
            if clean in stocks:
                s = stocks[clean]
                mapping[name] = {
                    'code': s['code'],
                    'short_name': s['short_name'],
                    'eng_abbrev': s['eng_abbrev'],
                    'full_name': s['full_name'],
                    'market': s['market'],
                    'match_method': 'ticker_cleaned',
                }
                break

print(f"Matched by ticker: {len(mapping)}")

# ── Step 2: Manual mapping for remaining ──
# These are companies with no ticker in NBIM or whose tickers aren't in either exchange
# (delisted, merged, renamed, or historical)
MANUAL = {
    'Government of Taiwan': ('GOV', '台灣政府公債', 'Gov of Taiwan', 'N/A'),
    # Major companies (no ticker in some periods)
    'Advanced Semiconductor Engineering Inc': ('2311', '日月光', 'ASE', 'TWSE'),
    'Advanced Semiconductor Engr': ('2311', '日月光', 'ASE', 'TWSE'),
    'ASE Test Ltd': ('2311', '日月光', 'ASE', 'TWSE'),
    'ASE Technology Holding Co Ltd': ('3711', '日月光投控', 'ASE Technology', 'TWSE'),
    'AU Optronics Corp': ('2409', '友達', 'AUO', 'TWSE'),
    'AUO Corp': ('2409', '友達', 'AUO', 'TWSE'),
    'HON HAI Precision Industry': ('2317', '鴻海', 'Hon Hai', 'TWSE'),
    'HON HAI Precision Industry Co Ltd': ('2317', '鴻海', 'Hon Hai', 'TWSE'),
    'Hon Hai Precision Industry': ('2317', '鴻海', 'Hon Hai', 'TWSE'),
    'Hon Hai Precision Industry Co Ltd': ('2317', '鴻海', 'Hon Hai', 'TWSE'),
    'HTC Corp': ('2498', '宏達電', 'HTC', 'TWSE'),
    'High Tech Computer Corp': ('2498', '宏達電', 'HTC', 'TWSE'),
    'Taiwan Semiconductor Manufacturing Co Ltd': ('2330', '台積電', 'TSMC', 'TWSE'),
    'Taiwan Semiconductor Manufacturing Company': ('2330', '台積電', 'TSMC', 'TWSE'),
    'TSMC Global Ltd': ('2330', '台積電', 'TSMC', 'TWSE'),
    'Chunghwa Telecom Co Ltd': ('2412', '中華電', 'CHT', 'TWSE'),
    'MediaTek Inc': ('2454', '聯發科', 'MediaTek', 'TWSE'),
    'United Microelectronics Corp': ('2303', '聯電', 'UMC', 'TWSE'),
    'United Micro Electronics Coporations Ltd': ('2303', '聯電', 'UMC', 'TWSE'),
    'Delta Electronics Inc': ('2308', '台達電', 'Delta', 'TWSE'),
    'Delta Electronic Industrial': ('2308', '台達電', 'Delta', 'TWSE'),
    'Quanta Computer': ('2382', '廣達', 'Quanta', 'TWSE'),
    'Quanta Computer Inc': ('2382', '廣達', 'Quanta', 'TWSE'),
    'Compal Electronics Inc': ('2324', '仁寶', 'Compal', 'TWSE'),
    'Compal Electronic Inc': ('2324', '仁寶', 'Compal', 'TWSE'),
    'Asustek Computer Inc': ('2357', '華碩', 'ASUSTeK', 'TWSE'),
    'Micro-Star International Co Ltd': ('2377', '微星', 'MSI', 'TWSE'),
    'Pegatron Corp': ('4938', '和碩', 'Pegatron', 'TWSE'),
    'Wistron Corp': ('3231', '緯創', 'Wistron', 'TWSE'),
    'Wiwynn Corp': ('6669', '緯穎', 'Wiwynn', 'TWSE'),
    'Inventec Corp': ('2356', '英業達', 'Inventec', 'TWSE'),
    'Inventec Co Ltd': ('2356', '英業達', 'Inventec', 'TWSE'),
    'Acer Inc': ('2353', '宏碁', 'Acer', 'TWSE'),
    'Foxconn Technology Co Ltd': ('2354', '鴻準', 'Foxconn Tech', 'TWSE'),
    'Cathay Financial Hldg Co': ('2882', '國泰金', 'Cathay FHC', 'TWSE'),
    'Cathay Financial Holding Co Ltd': ('2882', '國泰金', 'Cathay FHC', 'TWSE'),
    'Fubon Financial Holding Co Ltd': ('2881', '富邦金', 'Fubon FHC', 'TWSE'),
    'Mega Financial Holding Co Ltd': ('2886', '兆豐金', 'Mega FHC', 'TWSE'),
    'CTBC Financial Holding Co Ltd': ('2891', '中信金', 'CTBC FHC', 'TWSE'),
    'Chinatrust Financial Holding C': ('2891', '中信金', 'CTBC FHC', 'TWSE'),
    'Chinatrust Financial Holding Co': ('2891', '中信金', 'CTBC FHC', 'TWSE'),
    'Chinatrust Financial Holding Co Ltd': ('2891', '中信金', 'CTBC FHC', 'TWSE'),
    'China Trust Commercial Bank': ('2891', '中信金', 'CTBC FHC', 'TWSE'),
    'Chinatrust Commercial Bank Hong Kong': ('2891', '中信金', 'CTBC FHC', 'TWSE'),
    'E.Sun Financial Holding Co Ltd': ('2884', '玉山金', 'E.Sun FHC', 'TWSE'),
    'E.Sun Financial Holdings Co Ltd': ('2884', '玉山金', 'E.Sun FHC', 'TWSE'),
    'First Financial Holding Co Ltd': ('2892', '第一金', 'First FHC', 'TWSE'),
    'First Bank': ('2892', '第一金', 'First FHC', 'TWSE'),
    'First Commercial Bank': ('2892', '第一金', 'First FHC', 'TWSE'),
    'Hua Nan Financial Hldgs Co': ('2880', '華南金', 'Hua Nan FHC', 'TWSE'),
    'Hua Nan Financial Holdings Co Ltd': ('2880', '華南金', 'Hua Nan FHC', 'TWSE'),
    'Taishin Financial Holding Co Ltd': ('2887', '台新金', 'Taishin FHC', 'TWSE'),
    'Taishin Financial Holdings Co Ltd': ('2887', '台新金', 'Taishin FHC', 'TWSE'),
    'SinoPac Financial Holdings Co Ltd': ('2890', '永豐金', 'SinoPac FHC', 'TWSE'),
    'Sinopac Holdings Co': ('2890', '永豐金', 'SinoPac FHC', 'TWSE'),
    'Shin Kong Financial Holding Co Ltd': ('2888', '新光金', 'Shin Kong FHC', 'TWSE'),
    'Shin Kong Financial Holdings Co Ltd': ('2888', '新光金', 'Shin Kong FHC', 'TWSE'),
    'Shin Kong Life Insurance Company': ('2888', '新光金', 'Shin Kong FHC', 'TWSE'),
    'China Development Financial Hldgs': ('2883', '開發金', 'CDIB FHC', 'TWSE'),
    'China Development Financial Holding Corp': ('2883', '開發金', 'CDIB FHC', 'TWSE'),
    'KGI Financial Holding Co Ltd': ('2883', '開發金', 'KGI FHC', 'TWSE'),
    'Taiwan Cooperative Financial Holding': ('5880', '合庫金', 'TCB FHC', 'TWSE'),
    'Taiwan Cooperative Financial Holding Co Ltd': ('5880', '合庫金', 'TCB FHC', 'TWSE'),
    'Taiwan Cooperative Bank': ('5880', '合庫金', 'TCB FHC', 'TWSE'),
    'IBF Financial Holdings Co Ltd': ('2889', '國票金', 'IBF FHC', 'TWSE'),
    'Waterland Financial Holdings': ('2897', '王道銀行', 'O-Bank', 'TWSE'),
    'Waterland Financial Holdings Co Ltd': ('2897', '王道銀行', 'O-Bank', 'TWSE'),
    'Fuh-Hwa Financial Holdings Co Ltd': ('2897', '王道銀行', 'O-Bank', 'TWSE'),
    'Fuhwa Financial Holdings Co Ltd': ('2897', '王道銀行', 'O-Bank', 'TWSE'),
    'TS Financial Holding Co Ltd': ('2887', '台新金', 'Taishin FHC', 'TWSE'),
    'Jih Sun Financial Holdings Co Ltd': ('5820', '日盛金', 'Jih Sun FHC', 'TWSE'),
    'Yuanta Core Pacific Securities Co': ('2885', '元大金', 'Yuanta FHC', 'TWSE'),
    'China Steel Corp': ('2002', '中鋼', 'CSC', 'TWSE'),
    'China Steel Corporation': ('2002', '中鋼', 'CSC', 'TWSE'),
    'Formosa Plastics Corp': ('1301', '台塑', 'FPC', 'TWSE'),
    'Formosa Plastics Corporation': ('1301', '台塑', 'FPC', 'TWSE'),
    'Nan Ya Plastic Corp': ('1303', '南亞', 'NPC', 'TWSE'),
    'Nan Ya Plastics Corp': ('1303', '南亞', 'NPC', 'TWSE'),
    'Formosa Chemicals & Fibre Co': ('1326', '台化', 'FCFC', 'TWSE'),
    'Formosa Chemicals & Fibre Corp': ('1326', '台化', 'FCFC', 'TWSE'),
    'Formosa Chemicals & Fibre Corporation': ('1326', '台化', 'FCFC', 'TWSE'),
    'Formosa Petrochemical Corp': ('6505', '台塑化', 'FPCC', 'TWSE'),
    'Far Eastern New Century Corp': ('1402', '遠東新', 'FENC', 'TWSE'),
    'Far Eastern Textile': ('1402', '遠東新', 'FENC', 'TWSE'),
    'Far Eastern Textile Co Ltd': ('1402', '遠東新', 'FENC', 'TWSE'),
    'Evergreen Marine Corp': ('2603', '長榮', 'EMC', 'TWSE'),
    'Evergreen Marine Corp Taiwan Ltd': ('2603', '長榮', 'EMC', 'TWSE'),
    'Evergreen Marine Corp Tawain Ltd': ('2603', '長榮', 'EMC', 'TWSE'),
    'China Airlines': ('2610', '華航', 'China Airlines', 'TWSE'),
    'China Airlines Ltd': ('2610', '華航', 'China Airlines', 'TWSE'),
    'Eva Airways Corp': ('2618', '長榮航', 'EVA Air', 'TWSE'),
    'Yang Ming Marine Transport': ('2609', '陽明', 'Yang Ming', 'TWSE'),
    'Yang Ming Marine Transport Corp': ('2609', '陽明', 'Yang Ming', 'TWSE'),
    'Wan Hai Lines Ltd': ('2615', '萬海', 'Wan Hai', 'TWSE'),
    'Taiwan Mobile Co Ltd': ('3045', '台灣大', 'TWM', 'TWSE'),
    'Taiwan Cellular Corp': ('3045', '台灣大', 'TWM', 'TWSE'),
    'Uni-President Enterprises Co': ('1216', '統一', 'UPEC', 'TWSE'),
    'Uni-President Enterprises Corp': ('1216', '統一', 'UPEC', 'TWSE'),
    'Pou Chen Corp': ('9904', '寶成', 'Pou Chen', 'TWSE'),
    'POU Chen Corp': ('9904', '寶成', 'Pou Chen', 'TWSE'),
    'Taiwan Cement Corp': ('1101', '台泥', 'TCC', 'TWSE'),
    'TCC Group Holdings': ('1101', '台泥', 'TCC', 'TWSE'),
    'TCC Group Holdings Co Ltd': ('1101', '台泥', 'TCC', 'TWSE'),
    'Asia Cement Corp': ('1102', '亞泥', 'ACC', 'TWSE'),
    'Chia Hsin Cement Corp': ('1103', '嘉泥', 'CHC', 'TWSE'),
    'Innolux Corp': ('3481', '群創', 'Innolux', 'TWSE'),
    'InnoLux Display Corp': ('3481', '群創', 'Innolux', 'TWSE'),
    'Chimei Innolux Corp': ('3481', '群創', 'Innolux', 'TWSE'),
    'Chi Mei Optoelectronics Corp': ('3481', '群創', 'CMO', 'TWSE'),
    'E Ink Holdings Inc': ('8069', '元太', 'E Ink', 'TWSE'),
    'Largan Precision Co Ltd': ('3008', '大立光', 'Largan', 'TWSE'),
    'Novatek Microelectronics Corp': ('3034', '聯詠', 'Novatek', 'TWSE'),
    'Novatek Microelectronics Corp Ltd': ('3034', '聯詠', 'Novatek', 'TWSE'),
    'Realtek Semiconductor Corp': ('2379', '瑞昱', 'Realtek', 'TWSE'),
    'Realtek Semiconductor Corporation': ('2379', '瑞昱', 'Realtek', 'TWSE'),
    'Unimicron Technology Corp': ('3037', '欣興', 'Unimicron', 'TWSE'),
    'Nanya Technology Corp': ('2408', '南亞科', 'Nanya Tech', 'TWSE'),
    'Vanguard International Semiconductor Corp': ('5347', '世界先進', 'VIS', 'TWSE'),
    'Vanguard International Semiconductor Corporation': ('5347', '世界先進', 'VIS', 'TWSE'),
    'Lite-On Technology Corp': ('2301', '光寶科', 'Lite-On', 'TWSE'),
    'LITE-ON IT Corp': ('2301', '光寶科', 'Lite-On', 'TWSE'),
    'Lite-On IT Corp': ('2301', '光寶科', 'Lite-On', 'TWSE'),
    'Lite-On Semiconductor Corp': ('5305', '敦南', 'Lite-On Semi', 'OTC'),
    'Silergy Corp': ('6415', '矽力-KY', 'Silergy', 'TWSE'),
    'Winbond Electronics Corp': ('2344', '華邦電', 'Winbond', 'TWSE'),
    'Winbond Electronics Corporation': ('2344', '華邦電', 'Winbond', 'TWSE'),
    'Phison Electronics Corp': ('8299', '群聯', 'Phison', 'TWSE'),
    'Advantech Co Ltd': ('2395', '研華', 'Advantech', 'TWSE'),
    'Accton Technology Corp': ('2345', '智邦', 'Accton', 'TWSE'),
    'Gigabyte Technology Co Ltd': ('2376', '技嘉', 'Gigabyte', 'TWSE'),
    'Yageo Corp': ('2327', '國巨', 'Yageo', 'TWSE'),
    'Chailease Holding Co Ltd': ('5871', '中租-KY', 'Chailease', 'TWSE'),
    'Globalwafers Co Ltd': ('6488', '環球晶', 'GlobalWafers', 'TWSE'),
    'Taiwan High Speed Rail Corp': ('2633', '台灣高鐵', 'THSRC', 'TWSE'),
    'President Chain Store Corp': ('2912', '統一超', 'PCSC', 'TWSE'),
    'Far EasTone Telecommunications Co Ltd': ('4904', '遠傳', 'FET', 'TWSE'),
    'Asia Pacific Telecom Co Ltd': ('3682', '亞太電', 'APT', 'TWSE'),
    'Powertech Technology Inc': ('6239', '力成', 'PTI', 'TWSE'),
    'King Yuan Electronics Co Ltd': ('2449', '京元電', 'KYEC', 'TWSE'),
    'Chipbond Technology Corp': ('6147', '頎邦', 'Chipbond', 'TWSE'),
    'ChipMOS TECHNOLOGIES INC': ('8150', '南茂', 'ChipMOS', 'TWSE'),
    'ChipMOS TECHNOLOGIES Bermuda Ltd': ('8150', '南茂', 'ChipMOS', 'TWSE'),
    'ChipMOS Technologies Inc': ('8150', '南茂', 'ChipMOS', 'TWSE'),
    'Siliconware Precision Industries Co': ('2325', '矽品', 'SPIL', 'TWSE'),
    'Siliconware Precision Industries Co Ltd': ('2325', '矽品', 'SPIL', 'TWSE'),
    'Macronix International': ('2337', '旺宏', 'MXIC', 'TWSE'),
    'Macronix International Co Ltd': ('2337', '旺宏', 'MXIC', 'TWSE'),
    'Catcher Technology Co Ltd': ('2474', '可成', 'Catcher', 'TWSE'),
    'Eclat Textile Co Ltd': ('1476', '儒鴻', 'Eclat', 'TWSE'),
    'Hotai Motor Co Ltd': ('2207', '和泰車', 'Hotai', 'TWSE'),
    'Voltronic Power Technology Corp': ('6409', '旭隼', 'Voltronic', 'TWSE'),
    'Simplo Technology Co Ltd': ('6121', '新普', 'Simplo', 'TWSE'),
    'Feng TAY Enterprise Co Ltd': ('9910', '豐泰', 'Feng Tay', 'TWSE'),
    'Cheng Shin Rubber Industry Co Ltd': ('2105', '正新', 'CSR', 'TWSE'),
    'WPG Holdings Co Ltd': ('3702', '大聯大', 'WPG', 'TWSE'),
    'WPG Holdings Ltd': ('3702', '大聯大', 'WPG', 'TWSE'),
    'WT Microelectronics Co Ltd': ('3036', '文曄', 'WT', 'TWSE'),
    'Tripod Technology Corp': ('3044', '健鼎', 'Tripod', 'TWSE'),
    'Nan Ya Printed Circuit Board Corp': ('8046', '南電', 'NYPCB', 'TWSE'),
    'Compeq Manufacturing Co': ('2313', '華通', 'Compeq', 'TWSE'),
    'Compeq Manufacturing Co Ltd': ('2313', '華通', 'Compeq', 'TWSE'),
    'Zhen Ding Technology Holding Ltd': ('4958', '臻鼎-KY', 'ZDT', 'TWSE'),
    'Elan Microelectronics Corp': ('2458', '義隆', 'ELAN', 'TWSE'),
    'Richtek Technology Corp': ('6286', '立錡', 'Richtek', 'TWSE'),
    'Faraday Technology Corp': ('3035', '智原', 'Faraday', 'TWSE'),
    'Parade Technologies Ltd': ('4966', '譜瑞-KY', 'Parade', 'TWSE'),
    'Via Technologies Inc': ('2388', '威盛', 'VIA', 'TWSE'),
    'Via Technologies Incorporated': ('2388', '威盛', 'VIA', 'TWSE'),
    'Silicon Integrated Systems Corp': ('2363', '矽統', 'SiS', 'TWSE'),
    'Etron Technology Inc': ('5351', '鈺創', 'Etron', 'TWSE'),
    'ENNOSTAR Inc': ('3714', '富采', 'ENNOSTAR', 'TWSE'),
    'Ennostar Inc': ('3714', '富采', 'ENNOSTAR', 'TWSE'),
    'Walsin Lihwa Corp': ('1605', '華新', 'Walsin', 'TWSE'),
    'Walsin Technology Corp': ('2492', '華新科', 'Walsin Tech', 'TWSE'),
    'China Petrochemical Development Corp': ('1314', '中石化', 'CPDC', 'TWSE'),
    'China Synthetic Rubber Corp': ('1309', '台橡', 'CSRC', 'TWSE'),
    'China Man-Made Fiber Corp': ('1718', '中纖', 'CMMF', 'TWSE'),
    'China Manmade Fibers': ('1718', '中纖', 'CMMF', 'TWSE'),
    'China Manmade Fibers Corp': ('1718', '中纖', 'CMMF', 'TWSE'),
    'China General Plastics Corp': ('1305', '華夏', 'CGPC', 'TWSE'),
    'China Motor Corp': ('2204', '中華', 'CMC', 'TWSE'),
    'China Motor Corp Ltd': ('2204', '中華', 'CMC', 'TWSE'),
    'China Motors Co': ('2204', '中華', 'CMC', 'TWSE'),
    'China Life Insurance Co Ltd/Taiwan': ('2823', '中壽', 'China Life', 'TWSE'),
    'China Chemical & Pharmaceutical Co Ltd': ('1701', '中化', 'CCPC', 'TWSE'),
    'China Steel Chemical Corp': ('1726', '永記', 'CSCC', 'TWSE'),
    'China Electric Manufacturing Corp': ('1611', '中電', 'CEM', 'TWSE'),
    'China Bills Finance Corp': ('2820', '華票', 'CBFC', 'TWSE'),
    'Teco Electric & Machinery': ('1504', '東元', 'TECO', 'TWSE'),
    'Teco Electric and Machinery Co Ltd': ('1504', '東元', 'TECO', 'TWSE'),
    'Tatung Co Ltd': ('2371', '大同', 'Tatung', 'TWSE'),
    'Sampo Corp': ('1604', '聲寶', 'Sampo', 'TWSE'),
    'Standard Foods Corp': ('1227', '佳格', 'Standard Foods', 'TWSE'),
    'Wei Chuan Food Corp': ('1201', '味全', 'Wei Chuan', 'TWSE'),
    'Wei Chuan Foods Corp': ('1201', '味全', 'Wei Chuan', 'TWSE'),
    'Great Wall Enterprise Co': ('1210', '大成', 'Great Wall', 'TWSE'),
    'Great Wall Enterprise Co Ltd': ('1210', '大成', 'Great Wall', 'TWSE'),
    'Charoen Pokphand Enterprise': ('1215', '卜蜂', 'CPE', 'TWSE'),
    'AGV Products Corp': ('1217', '愛之味', 'AGV', 'TWSE'),
    'Hey Song Corp': ('1234', '黑松', 'Hey Song', 'TWSE'),
    'Lien Hwa Industrial Corp': ('1229', '聯華', 'LHIC', 'TWSE'),
    'Lien Hwa Industrial Holdings Corp': ('1229', '聯華', 'LHIC', 'TWSE'),
    'Lian HWA Food Corp': ('1231', '聯華食', 'Lian Hwa', 'TWSE'),
    'Taiwan Cement Corp': ('1101', '台泥', 'TCC', 'TWSE'),
    'Hsing TA Cement Co': ('1109', '信大', 'Hsing Ta', 'TWSE'),
    'Southeast Cement Co Ltd': ('1110', '東泥', 'Southeast', 'TWSE'),
    'Universal Cement Corp': ('1104', '環泥', 'UCC', 'TWSE'),
    'USI Corp': ('1304', '台聚', 'USI', 'TWSE'),
    'Asia Polymer': ('1308', '亞聚', 'Asia Polymer', 'TWSE'),
    'Asia Polymer Corp': ('1308', '亞聚', 'Asia Polymer', 'TWSE'),
    'Taiwan Styrene Monomer': ('1310', '台苯', 'TSM', 'TWSE'),
    'Grand Pacific Petrochemical': ('1312', '國喬', 'GPPC', 'TWSE'),
    'UPC Technology Corp': ('1313', '聯成', 'UPC', 'TWSE'),
    'LCY Chemical Corp': ('1704', '榮化', 'LCY', 'TWSE'),
    'LEE Chang Yung Chem IND Corp': ('1704', '榮化', 'LCY', 'TWSE'),
    'Oriental Union Chemical': ('1710', '東聯', 'OUCC', 'TWSE'),
    'Oriental Union Chemical Corp': ('1710', '東聯', 'OUCC', 'TWSE'),
    'Eternal Chemical Co Ltd': ('1717', '永光', 'Eternal', 'TWSE'),
    'Eternal Materials Co Ltd': ('1717', '永光', 'Eternal', 'TWSE'),
    'Shinkong Synthetic Fibers Corp': ('1409', '新纖', 'SSFC', 'TWSE'),
    'Shinkong Textile Co Ltd': ('1409', '新纖', 'SSFC', 'TWSE'),
    'Li Peng Enterprise Co Ltd': ('1431', '力鵬', 'Li Peng', 'TWSE'),
    'Nien Hsing Textile Co Ltd': ('1451', '年興', 'Nien Hsing', 'TWSE'),
    'Formosa Taffeta Co': ('1434', '福懋', 'FTC', 'TWSE'),
    'Formosa Taffeta Co Ltd': ('1434', '福懋', 'FTC', 'TWSE'),
    'Formosa International Hotels Corp': ('2707', '晶華', 'FIH', 'TWSE'),
    'Formosa Epitaxy Inc': ('3061', '璨圓', 'Formosa Epitaxy', 'OTC'),
    'Formosa Sumco Technology Corp': ('3532', '台勝科', 'Formosa Sumco', 'TWSE'),
    'Formosan Rubber Group Inc': ('2105', '正新', 'FRG', 'TWSE'),
    'Pacific Electric Wire & Cable Co Ltd': ('1603', '華電', 'PEWC', 'TWSE'),
    'Pacific Electrical Wire & Cable': ('1603', '華電', 'PEWC', 'TWSE'),
    'HUA ENG Wire & Cable': ('1608', '華榮', 'Hua Eng', 'TWSE'),
    'HUA ENG Wire & Cable Co Ltd': ('1608', '華榮', 'Hua Eng', 'TWSE'),
    'Tung Ho Steel Enterprise Corp': ('2006', '東鋼', 'Tung Ho', 'TWSE'),
    'Feng Hsin Iron & Steel Co': ('2015', '豐興', 'Feng Hsin', 'TWSE'),
    'Feng Hsin Steel Co Ltd': ('2015', '豐興', 'Feng Hsin', 'TWSE'),
    'Century Iron & Steel Industrial Co Ltd': ('9958', '世紀鋼', 'Century', 'TWSE'),
    'Hsin Kuang Steel Co Ltd': ('2031', '新光鋼', 'Hsin Kuang', 'TWSE'),
    'TA Chen Stainless Pipe': ('2027', '大成鋼', 'Ta Chen', 'TWSE'),
    'YC INOX Co Ltd': ('2012', '春雨', 'YC Inox', 'TWSE'),
    'Sheng Yu Steel Co Ltd': ('2029', '盛餘', 'Sheng Yu', 'TWSE'),
    'Yieh Phui Enterprise': ('2023', '燁輝', 'Yieh Phui', 'TWSE'),
    'Yieh Phui Enterprise Co Ltd': ('2023', '燁輝', 'Yieh Phui', 'TWSE'),
    'China Metal Products': ('2014', '中鴻', 'CMP', 'TWSE'),
    'Chun Yuan Steel': ('2010', '春源', 'Chun Yuan', 'TWSE'),
    'Chun Yuan Steel Industry Co Ltd': ('2010', '春源', 'Chun Yuan', 'TWSE'),
    'EVERGREEN Steel Corp': ('2211', '長榮鋼', 'Evergreen Steel', 'TWSE'),
    'Chung Hung Steel Corp': ('2014', '中鴻', 'CHS', 'TWSE'),
    'Far Eastern Department Stores Co Ltd': ('2903', '遠百', 'FEDS', 'TWSE'),
    'Far Eastern Department Stores Ltd': ('2903', '遠百', 'FEDS', 'TWSE'),
    'Far Eastern International Bank': ('2845', '遠東銀', 'FEIB', 'TWSE'),
    'FAR Eastern International Bank': ('2845', '遠東銀', 'FEIB', 'TWSE'),
    'Nan Kang Rubber Tire Co Ltd': ('2101', '南港', 'NKRT', 'TWSE'),
    'Giant Manufacturing': ('9921', '巨大', 'Giant', 'TWSE'),
    'Giant Manufacturing Co Ltd': ('9921', '巨大', 'Giant', 'TWSE'),
    'Merida Industry Co Ltd': ('9914', '美利達', 'Merida', 'TWSE'),
    'Johnson Health Tech Co Ltd': ('1736', '喬山', 'Johnson', 'TWSE'),
    'Sanyang Industrial Co Ltd': ('2206', '三陽', 'SYM', 'TWSE'),
    'Sanyang Industry Co Ltd': ('2206', '三陽', 'SYM', 'TWSE'),
    'Sanyang Motor Co Ltd': ('2206', '三陽', 'SYM', 'TWSE'),
    'Tong Yang Industry': ('1319', '東陽', 'TYC', 'TWSE'),
    'Tong Yang Industry Co Ltd': ('1319', '東陽', 'TYC', 'TWSE'),
    'Depo Auto Parts Ind Co Ltd': ('6605', '帝寶', 'Depo', 'TWSE'),
    'Hota Industrial Manufacturing Co Ltd': ('1536', '和大', 'Hota', 'TWSE'),
    'Hotai Finance Co Ltd': ('2207', '和泰車', 'Hotai', 'TWSE'),
    'Yulon Motor Co': ('2201', '裕隆', 'Yulon', 'TWSE'),
    'Yulon Motor Co Ltd': ('2201', '裕隆', 'Yulon', 'TWSE'),
    'Yulon Nissan Motor Co Ltd': ('2201', '裕隆', 'Yulon', 'TWSE'),
    'Yulon Finance Corp': ('9941', '裕融', 'Yulon Finance', 'TWSE'),
    'Highwealth Construction Corp': ('2542', '興富發', 'Highwealth', 'TWSE'),
    'Kindom Construction Corp': ('2520', '冠德', 'Kindom', 'TWSE'),
    'Kindom Construction Co': ('2520', '冠德', 'Kindom', 'TWSE'),
    'Kindom Development Co Ltd': ('2520', '冠德', 'Kindom', 'TWSE'),
    'Kingdom Construction Co': ('2520', '冠德', 'Kindom', 'TWSE'),
    'Huaku Development Co Ltd': ('2548', '華固', 'Huaku', 'TWSE'),
    'Huaku Construction Corp': ('2548', '華固', 'Huaku', 'TWSE'),
    'Ruentex Development Co Ltd': ('9945', '潤泰新', 'Ruentex Dev', 'TWSE'),
    'Ruentex Industries Ltd': ('2915', '潤泰全', 'Ruentex', 'TWSE'),
    'Prince Housing & Development Corp': ('2511', '太子', 'Prince', 'TWSE'),
    'Prince Housing Development Corp': ('2511', '太子', 'Prince', 'TWSE'),
    'Farglory Land Development Co Ltd': ('5522', '遠雄', 'Farglory', 'TWSE'),
    'Cathay Real Estate Development Co Ltd': ('2501', '國建', 'Cathay RE', 'TWSE'),
    'Chang Hwa Bank': ('2801', '彰銀', 'CHB', 'TWSE'),
    'Chang Hwa Commercial Bank': ('2801', '彰銀', 'CHB', 'TWSE'),
    'Chang Hwa Commercial Bank Ltd': ('2801', '彰銀', 'CHB', 'TWSE'),
    'Shanghai Commercial & Savings Bank Ltd/The': ('5876', '上海商銀', 'SCSB', 'TWSE'),
    'Taichung Commercial Bank': ('2812', '台中銀', 'Taichung Bank', 'TWSE'),
    'Taichung Commercial Bank Co Ltd': ('2812', '台中銀', 'Taichung Bank', 'TWSE'),
    'Taiwan Business Bank': ('2834', '臺企銀', 'TBB', 'TWSE'),
    'Bank of Kaohsiung': ('2836', '高雄銀', 'BoK', 'TWSE'),
    'Bank of Kaohsiung Co Ltd': ('2836', '高雄銀', 'BoK', 'TWSE'),
    'Central Reinsurance Co Ltd': ('2851', '中再保', 'Central Re', 'TWSE'),
    'Taiwan Fire & Marine Insurance Co': ('2832', '台產', 'TFMI', 'TWSE'),
    'Taiwan Fire & Marine Insurance Co Ltd': ('2832', '台產', 'TFMI', 'TWSE'),
    'Shinkong Insurance Co Ltd': ('2850', '新保', 'SKI', 'TWSE'),
    'Taiwan Life Insurance Co Ltd': ('2823', '中壽', 'China Life', 'TWSE'),
    'Capital Securities Corp': ('6005', '群益證', 'Capital', 'TWSE'),
    'Concord Securities Co Ltd': ('6005', '群益證', 'Concord', 'TWSE'),
    'Concord Securities Corp': ('6005', '群益證', 'Concord', 'TWSE'),
    'President Securities Corp': ('2855', '統一證', 'PSC', 'TWSE'),
    'KGI Securities Co Ltd': ('2883', '開發金', 'KGI', 'TWSE'),
    'Masterlink Securities Corp': ('2856', '元富證', 'Masterlink', 'TWSE'),
    'Polaris Securities Co Ltd': ('2856', '元富證', 'Polaris', 'TWSE'),
    'Polaris Group': ('2856', '元富證', 'Polaris', 'TWSE'),
    'Taiwan Fertilizer Co Ltd': ('1722', '台肥', 'TFC', 'TWSE'),
    'Taiwan Glass Industrial Corp': ('1802', '台玻', 'TGI', 'TWSE'),
    'Taiwan Glass Industry Corp': ('1802', '台玻', 'TGI', 'TWSE'),
    'Ambassador Hotel/The': ('2704', '國賓', 'Ambassador', 'TWSE'),
    'Aerospace Industrial Development Corp': ('2208', '台船', 'AIDC', 'TWSE'),
    'CSBC Corp Taiwan': ('2208', '台船', 'CSBC', 'TWSE'),
    'Taiwan Secom': ('9917', '中保科', 'Taiwan Secom', 'TWSE'),
    'Taiwan Secom Co Ltd': ('9917', '中保科', 'Taiwan Secom', 'TWSE'),
    'Taiwan Shin Kong Security Co Ltd': ('9917', '中保科', 'Taiwan Secom', 'TWSE'),
    'Taiwan Sogo Shin Kong SEC': ('9917', '中保科', 'Taiwan Secom', 'TWSE'),
    'Cheng Loong Corp': ('1904', '正隆', 'Cheng Loong', 'TWSE'),
    'YFY Inc': ('1907', '永豐餘', 'YFY', 'TWSE'),
    'Yuen Foong Yu Paper Manufacturing Co Ltd': ('1907', '永豐餘', 'YFY', 'TWSE'),
    'Long Chen Paper Co Ltd': ('1907', '永豐餘投控', 'Long Chen', 'TWSE'),
    'Chung HWA Pulp': ('1905', '華紙', 'CHP', 'TWSE'),
    'Chung Hwa Pulp Corp': ('1905', '華紙', 'CHP', 'TWSE'),
    'Shihlin Paper Corp': ('1903', '士紙', 'Shihlin Paper', 'TWSE'),
    'Great Taipei Gas Co Ltd': ('9908', '大台北', 'Great Taipei Gas', 'TWSE'),
    'Shihlin Electric & Engineering Corp': ('1503', '士電', 'Shihlin', 'TWSE'),
    'Fortune Electric Co Ltd': ('1519', '華城', 'Fortune', 'TWSE'),
    'ENG Electric Co Ltd': ('1514', '亞力', 'ENG', 'TWSE'),
    'Chung Hsin Electric & Machinery Manufacturing Corp': ('1514', '亞力', 'CHEMM', 'TWSE'),
    'Chung-Hsin Electric & Machinery Manufacturing Corp': ('1514', '亞力', 'CHEMM', 'TWSE'),
    'Synnex Technology International Corp': ('2347', '聯強', 'Synnex', 'TWSE'),
    'Taiwan Navigation Co Ltd': ('2617', '台航', 'Taiwan Nav', 'TWSE'),
    'Chinese Maritime Transport Ltd': ('2612', '中航', 'CMT', 'TWSE'),
    'Sincere Navigation': ('2605', '新興', 'Sincere', 'TWSE'),
    'Sincere Navigation Corp': ('2605', '新興', 'Sincere', 'TWSE'),
    'U-Ming Marine Transport Corp': ('2606', '裕民', 'U-Ming', 'TWSE'),
    'Wisdom Marine Lines Co Ltd': ('2637', '慧洋-KY', 'WML', 'TWSE'),
    'Shih Wei Navigation Co Ltd': ('2613', '中櫃', 'Shih Wei', 'TWSE'),
    'Taiwan FamilyMart Co Ltd/Taiwan': ('5903', '全家', 'FamilyMart', 'TWSE'),
    'Makalot Industrial Co Ltd': ('1477', '聚陽', 'Makalot', 'TWSE'),
    'Fulgent Sun International Holding Co Ltd': ('9802', '鈺齊-KY', 'Fulgent Sun', 'TWSE'),
    'Evergreen International Storage & Transport Corp': ('2607', '榮運', 'EIST', 'TWSE'),
    'Evergreen Aviation Technologies Corp': ('2607', '榮運', 'EGAT', 'TWSE'),
    'Starlux Airlines Co Ltd': ('2646', '星宇航空', 'STARLUX', 'TWSE'),
    'Taiwan Cogeneration Corp': ('8926', '台汽電', 'TCC Gen', 'OTC'),
    'CTCI Corp': ('9933', '中鼎', 'CTCI', 'TWSE'),
    'Hiwin Technologies Corp': ('2049', '上銀', 'HIWIN', 'TWSE'),
    'Airtac International Group': ('1590', '亞德客-KY', 'AirTAC', 'TWSE'),
    'TPK Holding Co Ltd': ('3673', '宸鴻', 'TPK', 'TWSE'),
    'Pixart Imaging Inc': ('3227', '原相', 'PixArt', 'TWSE'),
    'Genesys Logic Inc': ('6104', '創惟', 'Genesys', 'OTC'),
    'Genius Electronic Optical Co Ltd': ('3406', '玉晶光', 'GSEO', 'TWSE'),
    'Global Unichip Corp': ('3443', '創意', 'GUC', 'TWSE'),
    'Alchip Technologies Ltd': ('3661', '世芯-KY', 'Alchip', 'TWSE'),
    'eMemory Technology Inc': ('3529', '力旺', 'eMemory', 'TWSE'),
    'M31 Technology Corp': ('6643', 'M31', 'M31', 'OTC'),
    'Win Semiconductors Corp': ('3105', '穩懋', 'Win Semi', 'TWSE'),
    'Chicony Electronics Co Ltd': ('2385', '群光', 'Chicony', 'TWSE'),
    'Chicony Power Technology Co Ltd': ('6670', '群光電能', 'Chicony Power', 'TWSE'),
    'PharmaEssentia Corp': ('6446', '藥華藥', 'PharmaEssentia', 'TWSE'),
    'PharmaEngine Inc': ('4160', '智擎', 'PharmaEngine', 'OTC'),
    'Medigen Vaccine Biologics Corp': ('6547', '高端疫苗', 'Medigen', 'OTC'),
    'Medigen Biotechnology Corp': ('4726', '永昕', 'Medigen Bio', 'OTC'),
    'TaiMed Biologics Inc': ('4147', '中裕', 'TaiMed', 'OTC'),
    'OBI Pharma Inc': ('4174', '浩鼎', 'OBI', 'OTC'),
    'Oneness Biotech Co Ltd': ('4743', '合一', 'Oneness', 'OTC'),
    'ScinoPharm Taiwan Ltd': ('1789', '神隆', 'ScinoPharm', 'TWSE'),
    'TTY Biopharm Co Ltd': ('4105', '東洋', 'TTY', 'TWSE'),
    'Bora Pharmaceuticals Co Ltd': ('6472', '保瑞', 'Bora', 'OTC'),
    'Center Laboratories Inc': ('4123', '晟德', 'Center Labs', 'OTC'),
    'Grape King Bio Ltd': ('1707', '葡萄王', 'Grape King', 'TWSE'),
    'Adimmune Corp': ('1795', '美時', 'Adimmune', 'OTC'),
    'momo.com Inc': ('8454', '富邦媒', 'momo', 'TWSE'),
    'PChome Online Inc': ('8044', '網家', 'PChome', 'TWSE'),
    'International Games System Co Ltd': ('3293', '鈊象', 'IGS', 'TWSE'),
    'Gamania Digital Entertainment Co Ltd': ('6180', '橘子', 'Gamania', 'OTC'),
    'Soft-World International Corp': ('2473', '思維', 'Soft-World', 'OTC'),
    'Chinese Gamer International Corp': ('2641', '正崴', 'Chinese Gamer', 'OTC'),
    'Test Rite International Co Ltd': ('2908', '特力', 'Test Rite', 'TWSE'),
    'Test-Rite International Co': ('2908', '特力', 'Test Rite', 'TWSE'),
    'Test-Rite International Co Ltd': ('2908', '特力', 'Test Rite', 'TWSE'),
    'Mercuries & Associates Holding Ltd': ('2905', '三商家購', 'Mercuries', 'TWSE'),
    'Mercuries & Associates Ltd': ('2905', '三商家購', 'Mercuries', 'TWSE'),
    'Mercuries Life Insurance Co Ltd': ('2905', '三商家購', 'Mercuries', 'TWSE'),
    'D-Link Corp': ('2332', '友訊', 'D-Link', 'TWSE'),
    'Alpha Networks Inc': ('3380', '明泰', 'Alpha', 'TWSE'),
    'Arcadyan Technology Corp': ('3596', '智易', 'Arcadyan', 'OTC'),
    'FLEXium Interconnect Inc': ('6269', '台郡', 'Flexium', 'TWSE'),
    'Chilisin Electronics Corp': ('2456', '奇力新', 'Chilisin', 'TWSE'),
    'Holy Stone Enterprise Co Ltd': ('3026', '禾伸堂', 'Holy Stone', 'TWSE'),
    'Holystone Enterprise Co Ltd': ('3026', '禾伸堂', 'Holy Stone', 'TWSE'),
    'Asia Vital Components Co Ltd': ('3017', '奇鋐', 'AVC', 'TWSE'),
    'AURAS Technology Co Ltd': ('3324', '雙鴻', 'AURAS', 'TWSE'),
    'Everlight Electronics Co Ltd': ('2393', '億光', 'Everlight', 'TWSE'),
    'Merry Electronics Co Ltd': ('2439', '美律', 'Merry', 'TWSE'),
    'Primax Electronics Ltd': ('4915', '致伸', 'Primax', 'TWSE'),
    'Kinpo Electronics': ('2312', '金寶', 'Kinpo', 'TWSE'),
    'Radiant Opto-Electronics Corp': ('6176', '瑞儀', 'Radiant', 'TWSE'),
    'Chroma ATE Inc': ('2360', '致茂', 'Chroma', 'TWSE'),
    'Nuvoton Technology Corp': ('4919', '新唐', 'Nuvoton', 'TWSE'),
    'Sinyi Realty Co': ('9940', '信義', 'Sinyi', 'TWSE'),
    'Sinyi Realty Inc': ('9940', '信義', 'Sinyi', 'TWSE'),
    'Chunghwa Picture Tubes': ('2475', '華映', 'CPT', 'TWSE'),
    'Chunghwa Picture Tubes Ltd': ('2475', '華映', 'CPT', 'TWSE'),
    'HannStar Display Corp': ('6116', '彩晶', 'HannStar', 'TWSE'),
    'Hannstar Display Corp': ('6116', '彩晶', 'HannStar', 'TWSE'),
    'Cheng Uei Precision Industry Co': ('2392', '正崴', 'Cheng Uei', 'TWSE'),
    'Cheng Uei Precision Industry Co Ltd': ('2392', '正崴', 'Cheng Uei', 'TWSE'),
    'Wah Lee Industrial Corp': ('3010', '華立', 'Wah Lee', 'TWSE'),
    'Elitegroup Computer Systems': ('2331', '精英', 'ECS', 'TWSE'),
    'Elitegroup Computer Systems Co Ltd': ('2331', '精英', 'ECS', 'TWSE'),
    'Mitac International': ('2315', '神達', 'MiTAC', 'TWSE'),
    'Mitac International Corp': ('2315', '神達', 'MiTAC', 'TWSE'),
    'Mitac Holdings Corp': ('3706', '神達投控', 'MiTAC Holdings', 'TWSE'),
    'Pan-International Industrial': ('2328', '廣宇', 'Pan-Intl', 'TWSE'),
    'Pan-International Industrial Corp': ('2328', '廣宇', 'Pan-Intl', 'TWSE'),
    'Sunplus Technology Co Ltd': ('2401', '凌陽', 'Sunplus', 'TWSE'),
    'Sunplus Technology Company Ltd': ('2401', '凌陽', 'Sunplus', 'TWSE'),
    'Holtek Semiconductor Inc': ('6202', '盛群', 'Holtek', 'TWSE'),
    'Transcend Information Inc': ('2451', '創見', 'Transcend', 'TWSE'),
    'ADATA Technology Co Ltd': ('3260', '威剛', 'ADATA', 'TWSE'),
    'A-DATA Technology Co Ltd': ('3260', '威剛', 'ADATA', 'TWSE'),
    'ITE Technology Inc': ('8213', 'ITE', 'ITE', 'OTC'),
    'CMC Magnetics Corp': ('2323', '中環', 'CMC', 'TWSE'),
    'Cmc Magnetics Corp': ('2323', '中環', 'CMC', 'TWSE'),
    'Ritek Corp': ('2349', '錸德', 'Ritek', 'TWSE'),
    'Ritek Incorporation': ('2349', '錸德', 'Ritek', 'TWSE'),
    'Orient Semiconductor Electronics Ltd': ('2329', '華泰', 'OSE', 'TWSE'),
    'Mosel Vitelic Inc': ('2342', '茂矽', 'Mosel', 'TWSE'),
    'Epistar Corp': ('2448', '晶電', 'Epistar', 'TWSE'),
    'Wistron NeWeb Corp': ('6285', '啟碁', 'WNC', 'TWSE'),
    'WNC Corp /Taiwan': ('6285', '啟碁', 'WNC', 'TWSE'),
    'Ennoconn Corp': ('6414', '樺漢', 'Ennoconn', 'TWSE'),
    'Tong Hsing Electronic Industries Ltd': ('6271', '同欣電', 'Tong Hsing', 'TWSE'),
    'Lotes Co Ltd': ('3533', '嘉澤', 'Lotes', 'TWSE'),
    'Sinbon Electronics Co Ltd': ('3023', '信邦', 'Sinbon', 'TWSE'),
    'Elite Material Co Ltd': ('2383', '台光電', 'EMC', 'TWSE'),
    'Gold Circuit Electronics Ltd': ('2368', '金像電', 'GCE', 'TWSE'),
    'WUS Printed Circuit Co Ltd': ('2316', '楠梓電', 'WUS', 'TWSE'),
    'Chin-Poon Industrial Co': ('2355', '敬鵬', 'Chin-Poon', 'TWSE'),
    'Chin-Poon Industrial Co Ltd': ('2355', '敬鵬', 'Chin-Poon', 'TWSE'),
    'Hu Lane Associate Inc': ('6279', '胡連', 'Hu Lane', 'TWSE'),
    'Cub Elecparts Inc': ('2231', '為升', 'Cub', 'TWSE'),
    'Tung Thih Electronic Co Ltd': ('3552', '同致', 'TTE', 'TWSE'),
    'Taiwan Taiwan PCB Techvest Co Ltd': ('8039', '台表科', 'TPT', 'OTC'),
    'Taiwan PCB Techvest Co Ltd': ('8039', '台表科', 'TPT', 'OTC'),
    'Taiwan Union Technology Corp': ('6274', '台燿', 'TUC', 'OTC'),
    'Taiwan Surface Mounting Technology Co Ltd': ('6278', '台表科', 'TSMT', 'OTC'),
    'Taiwan Surface Mounting Technology Corp': ('6278', '台表科', 'TSMT', 'OTC'),
    'Career Technology Co Ltd': ('6153', '嘉聯益', 'Career', 'TWSE'),
    'Career Technology MFG. Co Ltd': ('6153', '嘉聯益', 'Career', 'TWSE'),
    'Chunghwa Precision Test Tech Co Ltd': ('6510', '精測', 'CHPT', 'OTC'),
    'Darfon Electronics Corp': ('8163', '達方', 'Darfon', 'OTC'),
    'Shin Zu Shing Co Ltd': ('3376', '新日興', 'SZS', 'OTC'),
    'Senao International Co Ltd': ('2450', '神腦', 'Senao', 'TWSE'),
    'ASROCK Inc': ('3515', '華擎', 'ASRock', 'OTC'),
    'Coretronic Corp': ('5765', '中光電', 'Coretronic', 'TWSE'),
    'ASMedia Technology Inc': ('5765', '祥碩', 'ASMedia', 'TWSE'),
    'ASPEED Technology Inc': ('5274', '信驊', 'ASPEED', 'OTC'),
    'Getac Holdings Corp': ('3005', '神基', 'Getac', 'TWSE'),
    'Getac Technology Corp': ('3005', '神基', 'Getac', 'TWSE'),
    'Adlink Technology Inc': ('6166', '凌華', 'ADLINK', 'TWSE'),
    'Foxsemicon Integrated Technology Inc': ('3040', '遠茂', 'Foxsemicon', 'OTC'),
    'Hon Precision Inc': ('2354', '鴻準', 'Hon Precision', 'TWSE'),
    'Ardentec Corp': ('3264', '欣銓', 'Ardentec', 'OTC'),
    'Greatek Electronics Inc': ('2441', '超豐', 'Greatek', 'TWSE'),
    'Insyde Software Corp': ('6231', '系微', 'Insyde', 'OTC'),
    'Marketech International Corp': ('6196', '帆宣', 'Marketech', 'OTC'),
    'Test Research Inc': ('3030', '德律', 'TRI', 'TWSE'),
    'International Semiconductor Technology Ltd': ('3520', '振曜', 'IST', 'OTC'),
    'Sporton International Inc': ('6198', '精測', 'Sporton', 'TWSE'),
    'Integrated Service Technology Inc': ('6207', '耀鴻', 'IST', 'OTC'),
    'Eastern Media International Corp': ('2614', '東森', 'EMI', 'TWSE'),
    'Continental Engineering Corp': ('2535', '達欣工', 'Continental', 'TWSE'),
    'Continental Holdings Corp': ('3703', '欣陸', 'Continental Holdings', 'TWSE'),
    'United Integrated Services Co Ltd': ('2404', '漢唐', 'UIS', 'TWSE'),
    'Egis Technology Inc': ('6462', '神盾', 'Egis', 'TWSE'),
    'FocalTech Systems Co Ltd': ('3545', '敦泰', 'FocalTech', 'OTC'),
    'Aten International Co Ltd': ('6277', '宏正', 'ATEN', 'TWSE'),
    'IEI Integration Corp': ('3022', '威強電', 'IEI', 'OTC'),
    'ICP Electronics Inc': ('3023', '信邦', 'ICP', 'OTC'),
    'CHC Healthcare Group': ('4164', '承業', 'CHC', 'OTC'),
    'Wah Hong Industrial Corp': ('8240', '華宏', 'Wah Hong', 'OTC'),
    'Compal Communications Inc': ('8078', '華寶', 'Compal Comm', 'OTC'),
    'Inventec Appliances Corp': ('2356', '英業達', 'IAC', 'TWSE'),
    'FSP Technology Inc': ('3015', '全漢', 'FSP', 'OTC'),
    'Flytech Technology Co Ltd': ('6206', '飛捷', 'Flytech', 'OTC'),
    'Asia Optical Co Inc': ('3019', '亞光', 'Asia Optical', 'TWSE'),
    'Lingsen Precision Industries Ltd': ('2369', '菱生', 'Lingsen', 'TWSE'),
    'Wafer Works Corp': ('6182', '合晶', 'Wafer Works', 'OTC'),
    'Sino-American Silicon Products Inc': ('5483', '中美晶', 'SAS', 'TWSE'),
    'Taiwan Mask Corp': ('2338', '光罩', 'TMC', 'TWSE'),
    'Inotera Memories Inc': ('3474', '華亞科', 'Inotera', 'TWSE'),
    'Powerchip Semiconductor Corp': ('5765', '力晶', 'PSC', 'DELISTED'),
    'Powerchip Technology Corp': ('5765', '力晶', 'PSC', 'DELISTED'),
    'Powerchip Semiconductor Manufacturing Corp': ('6770', '力積電', 'PSMC', 'TWSE'),
    'Grape King Bio Ltd': ('1707', '葡萄王', 'Grape King', 'TWSE'),
    'Nan Liu Enterprise Co Ltd': ('1752', '南六', 'Nan Liu', 'OTC'),
    'Nan Pao Resins Chemical Co Ltd': ('4766', '南寶', 'Nan Pao', 'OTC'),
    'Tainan Enterprises Co Ltd': ('1473', '台南', 'Tainan', 'TWSE'),
    'Tainan Spinning Co Ltd': ('1440', '南紡', 'Tainan Spinning', 'TWSE'),
    'Lealea Enterprise Co Ltd': ('1444', '力麗', 'Lealea', 'TWSE'),
    'Kenda Rubber Industrial Co': ('2106', '建大', 'Kenda', 'TWSE'),
    'Kenda Rubber Industrial Co Ltd': ('2106', '建大', 'Kenda', 'TWSE'),
    'Ho Tung Chemical Corp': ('1714', '和桐', 'Ho Tung', 'TWSE'),
    'Zyxel Communications Corp': ('2391', '合勤', 'ZyXEL', 'TWSE'),
    'Taiwan Sakura Corp': ('9911', '櫻花', 'Sakura', 'TWSE'),
    'Airtac International Group': ('1590', '亞德客-KY', 'AirTAC', 'TWSE'),
    'Tsann Kuen Enterprise Co Ltd': ('2430', '燦坤', 'Tsann Kuen', 'TWSE'),
    'Poya Co Ltd': ('5904', '寶雅', 'Poya', 'OTC'),
    'Poya International Co Ltd': ('5904', '寶雅', 'Poya', 'OTC'),
    'Yungtay Engineering Co Ltd': ('1507', '永大', 'Yungtay', 'TWSE'),
    'Vivotek Inc': ('3454', '晶睿', 'VIVOTEK', 'OTC'),
    'EirGenix Inc': ('6589', '台康生技', 'EirGenix', 'OTC'),
    'Chenbro Micom Co Ltd': ('8210', '勤誠', 'Chenbro', 'OTC'),
    'AcBel Polytech Inc': ('6282', '康舒', 'AcBel', 'TWSE'),
    'AmTRAN Technology Co Ltd': ('2489', '瑞軒', 'AmTRAN', 'TWSE'),
    'Innodisk Corp': ('5765', '宜鼎', 'Innodisk', 'OTC'),
    'Universal Scientific Industrial Co Ltd': ('6145', '日月光投控', 'USI', 'TWSE'),
    'Hsinchu International Bank': ('2812', '台中銀', 'Hsinchu Bank', 'TWSE'),
    'Cosmos Bank Taiwan': ('2837', '萬泰銀', 'Cosmos', 'TWSE'),
    'Union Bank Of Taiwan': ('2838', '聯邦銀', 'Union Bank', 'TWSE'),
    'International Bank of Taipei': ('2845', '遠東銀', 'IBT', 'TWSE'),
    'O-Bank Co Ltd': ('2897', '王道銀行', 'O-Bank', 'TWSE'),
    'Ta Chong Bank Co Ltd': ('2847', '大眾銀', 'Ta Chong', 'TWSE'),
    'Ta Chong Bank Ltd': ('2847', '大眾銀', 'Ta Chong', 'TWSE'),
    'National Petroleum Co Ltd': ('1328', '國光化', 'NPC', 'OTC'),
    'Nien Hsing Textile Co Ltd': ('1451', '年興', 'Nien Hsing', 'TWSE'),
    'Nien Made Enterprise Co Ltd': ('8383', '千附', 'Nien Made', 'OTC'),
    'Nien Made Enterprises': ('8383', '千附', 'Nien Made', 'OTC'),
    'Clevo Co': ('2362', '藍天', 'Clevo', 'TWSE'),
    'Bright Led Electronics Corp': ('5765', '億光電', 'Bright LED', 'TWSE'),
    'Lextar Electronics Corp': ('3698', '隆達', 'Lextar', 'TWSE'),
    'TCI Co Ltd': ('8436', 'TCI', 'TCI', 'OTC'),
    'Tigerair Taiwan Co Ltd': ('6757', '台灣虎航', 'Tigerair', 'OTC'),
    'ASPEED Technology Inc': ('5274', '信驊', 'ASPEED', 'OTC'),
    'Hermes Microvision Inc': ('3658', '漢微科', 'HMI', 'OTC'),
    'Shin Foong Specialty & Applied Materials Co Ltd': ('5765', '信豐', 'Shin Foong', 'OTC'),
    'Bizlink Holding Inc': ('3665', '貿聯-KY', 'BizLink', 'TWSE'),
    'Sercomm Corp': ('5388', '中磊', 'Sercomm', 'OTC'),
    'Chief Telecom Inc': ('6561', '是方', 'Chief', 'OTC'),
    'Simplo Technology Co Ltd': ('6121', '新普', 'Simplo', 'TWSE'),
    'Chlitina Holding Ltd': ('4137', '克麗緹娜-KY', 'Chlitina', 'OTC'),
    '91APP Inc': ('6741', '91APP*-KY', '91APP', 'OTC'),
    'SDI Corp': ('2351', '順德', 'SDI', 'TWSE'),
    'Taiwan Paiho Ltd': ('9938', '百和', 'Paiho', 'TWSE'),
    'RichWave Technology Corp': ('4968', '立積', 'RichWave', 'OTC'),
    'VisEra Technologies Co Ltd': ('3030', '采鈺', 'VisEra', 'TWSE'),
    'ShunSin Technology Holding Ltd': ('6451', '順信-KY', 'ShunSin', 'OTC'),
    'Sunny Friend Environmental Technology Co Ltd': ('8341', '日友', 'Sunny Friend', 'OTC'),
    'Cleanaway Co Ltd': ('8422', '可寧衛', 'Cleanaway', 'OTC'),
    'GeneReach Biotechnology Corp': ('6568', '瑞基', 'GeneReach', 'OTC'),
    'Taiwan Liposome Co Ltd': ('4152', '台微體', 'TLC', 'OTC'),
    'Taiwan Semiconductor Co Ltd': ('5425', '台半', 'TSC', 'TWSE'),
    # Remaining 20 unmatched - mostly delisted/historical
    'Action Electronics Co Ltd': ('5765', '精英電', 'Action', 'DELISTED'),
    'Arima Photovoltaic & Optical Corp': ('5765', '華宇光', 'Arima PV', 'DELISTED'),
    'Co-Tech Development Corp': ('8358', '金居', 'Co-Tech', 'OTC'),
    'Dynapack International Technology Corp': ('3211', '順達科', 'Dynapack', 'OTC'),
    'Emerging Display Technologies Corp': ('5765', '彩面板', 'EDT', 'DELISTED'),
    'Fulltech Fiber Glass Corp': ('5765', '富喬', 'Fulltech', 'DELISTED'),
    'Genesis Photonics Inc': ('3383', '新世紀', 'Genesis', 'OTC'),
    'Grand Process Technology Corp': ('3131', '弘塑', 'GPT', 'OTC'),
    'Green Seal Holding Ltd': ('1262', '綠悅-KY', 'Green Seal', 'OTC'),
    'Kuo Toong International Co Ltd': ('8936', '國統', 'Kuo Toong', 'OTC'),
    'LuxNet Corp': ('4979', '華星光', 'LuxNet', 'OTC'),
    'P-Two Industries Inc': ('5765', 'P-Two', 'P-Two', 'DELISTED'),
    'Prime View International Co Ltd': ('5765', '元太', 'PVI', 'MERGED'),
    'Solar Applied Materials Technology Co': ('1785', '光洋科', 'Solar Applied', 'TWSE'),
    'Solar Applied Materials Technology Corp': ('1785', '光洋科', 'Solar Applied', 'TWSE'),
    'United World Chinese Commercial Bank': ('5765', '世華銀行', 'UWCCB', 'MERGED'),
    'Waffer Technology Co Ltd': ('5765', '圓益', 'Waffer', 'DELISTED'),
    'XinTec Inc': ('3374', '精材', 'XinTec', 'OTC'),
    'Chiao Tung Bank': ('5765', '交通銀行', 'Chiao Tung', 'MERGED'),
    'Farmers Bank of China Ltd/The': ('5765', '中國農民銀行', 'Farmers Bank', 'MERGED'),
    'International Commercial Bank Of China': ('5765', '中國國際商銀', 'ICBC', 'MERGED'),
    'Prodisc Technology Inc': ('5765', '精碟科技', 'Prodisc', 'DELISTED'),
    'ProMOS Technologies Inc': ('5765', '茂德科技', 'ProMOS', 'DELISTED'),
    'ProMos Technologies Inc': ('5765', '茂德科技', 'ProMOS', 'DELISTED'),
    'Promos Technologies Inc': ('5765', '茂德科技', 'ProMOS', 'DELISTED'),
    'Taiwan-Asia Semiconductor Corp': ('5765', '台亞半導體', 'TAS', 'DELISTED'),
    'MStar Semiconductor Inc': ('5765', '晨星半導體', 'MStar', 'MERGED'),
    'Ralink Technology Corp': ('5765', '雷凌科技', 'Ralink', 'MERGED'),
    'Springsoft Inc': ('5765', '思源科技', 'SpringSoft', 'MERGED'),
    'FIC Global Inc': ('5765', '大眾電腦', 'FIC', 'DELISTED'),
    'Behavior Technology Computer': ('5765', '英群企業', 'BTC', 'DELISTED'),
    'DBTEL Inc': ('5765', '大霸電子', 'DBTel', 'DELISTED'),
    'GigaMedia Ltd': ('5765', '和信超媒體', 'GigaMedia', 'DELISTED'),
    'Wintek Corp': ('5765', '勝華科技', 'Wintek', 'DELISTED'),
    'Wintek Corp/Taiwan': ('5765', '勝華科技', 'Wintek', 'DELISTED'),
    'Sintek Photronic Corp': ('5765', '新技光電', 'Sintek', 'DELISTED'),
    'Inotera Memories Inc': ('3474', '華亞科技', 'Inotera', 'MERGED'),
    'Hsinchu International Bank': ('2812', '新竹商銀', 'HIB', 'MERGED'),
    'Starlux Airlines Co Ltd': ('2646', '星宇航空', 'STARLUX', 'TWSE'),
    'King\'s Town Bank': ('2809', '京城銀行', 'Kings Town', 'TWSE'),
    'King\'s Town Bank Co Ltd': ('2809', '京城銀行', 'Kings Town', 'TWSE'),
    'King\'s Town Construction Co Ltd': ('2524', '京城建設', 'Kings Town Const', 'TWSE'),
    'Kings Town Bank': ('2809', '京城銀行', 'Kings Town Bank', 'TWSE'),
    'Kings Town Construction Co Ltd': ('2524', '京城建設', 'Kings Town Const', 'TWSE'),
    'Kuo Yang Construction Co Ltd': ('2505', '國揚', 'Kuo Yang', 'TWSE'),
    'Kuoyang Construction Co Ltd': ('2505', '國揚', 'Kuo Yang', 'TWSE'),
    'Hung Poo Real Estate Development Corp': ('2536', '宏普', 'Hung Poo', 'TWSE'),
    'Hung Sheng Construction Co Ltd': ('2534', '宏盛', 'Hung Sheng', 'TWSE'),
    'Hung Sheng Construction Ltd': ('2534', '宏盛', 'Hung Sheng', 'TWSE'),
    'Run Long Construction Co Ltd': ('1808', '潤隆', 'Run Long', 'TWSE'),
    'Chong Hong Construction Co': ('2530', '華建', 'Chong Hong', 'TWSE'),
    'Chong Hong Construction Co Ltd': ('2530', '華建', 'Chong Hong', 'TWSE'),
    'KEE TAI Properties Co Ltd': ('2596', '綠意', 'Kee Tai', 'TWSE'),
    'Lealea Enterprise Co Ltd': ('1444', '力麗', 'Lealea', 'TWSE'),
    'Shihlin Electric & Engineering Corp': ('1503', '士電', 'Shihlin', 'TWSE'),
    'Macronix International': ('2337', '旺宏', 'MXIC', 'TWSE'),
    'Macronix International Co Ltd': ('2337', '旺宏', 'MXIC', 'TWSE'),
    'BES Engineering Corp': ('2222', '福懋科', 'BES', 'TWSE'),
    'Dimerco Express Corp': ('5765', '中菲行', 'Dimerco', 'OTC'),
    'Kerry TJ Logistics Co Ltd': ('2608', '嘉里大榮', 'Kerry TJ', 'OTC'),
    'T3EX Global Holdings Corp': ('9938', '百和', 'T3EX', 'TWSE'),
    'First Hotel': ('2706', '第一店', 'First Hotel', 'TWSE'),
    'First Hi-Tec Enterprise Co Ltd': ('3388', '崇越電', 'First Hi-Tec', 'OTC'),
    'First International Computer Inc': ('2315', '神達', 'FIC', 'TWSE'),
    'First Steamship Co Ltd': ('2601', '益航', 'First Steamship', 'TWSE'),
    'JSL Construction & Development Co Ltd': ('2547', '日勝生', 'JSL', 'TWSE'),
    'L&K Engineering Co Ltd': ('6155', '鉅邦', 'L&K', 'OTC'),
    'CTCI Corp': ('9933', '中鼎', 'CTCI', 'TWSE'),
    'Rich Development Co Ltd': ('6008', '凱基', 'Rich Dev', 'TWSE'),
    'Sakura Development Co Ltd': ('2539', '櫻花建', 'Sakura Dev', 'TWSE'),
    'Long Bon Development Co Ltd': ('5765', '龍邦', 'Long Bon', 'TWSE'),
    'Long Bon International Co Ltd': ('5765', '龍邦', 'Long Bon', 'TWSE'),
    'Hong Pu Real Estate Development Co Ltd': ('2530', '華建', 'Hong Pu', 'TWSE'),
    'Star Comgistic Capital Co Ltd': ('2643', '星通', 'Star', 'TWSE'),
    'Taiwan Acceptance Corp': ('2834', '臺企銀', 'TBB', 'TWSE'),
    'T JOIN Transportation Co': ('5765', 'T JOIN', 'T JOIN', 'OTC'),
    'Casetek Holdings Ltd': ('5765', '鎧勝-KY', 'Casetek', 'MERGED'),
    'Taiwan Land Development Corp': ('2841', '台開', 'TLD', 'TWSE'),
    'Goldsun Building Materials Co Ltd': ('1805', '飛宏', 'Goldsun', 'TWSE'),
    'Champion Building Materials Co Ltd': ('1806', '冠軍', 'Champion', 'TWSE'),
    'Delpha Construction Co Ltd': ('2530', '長虹', 'Delpha', 'TWSE'),
}

# Apply manual mappings for everything not yet matched
for name in all_names:
    if name not in mapping and name in MANUAL:
        code, short_name, eng, market = MANUAL[name]
        mapping[name] = {
            'code': code,
            'short_name': short_name,
            'eng_abbrev': eng,
            'full_name': '',
            'market': market,
            'match_method': 'manual',
        }

# Final check
still_unmatched = [n for n in all_names if n not in mapping]
print(f"\nFinal results:")
print(f"  Total matched: {len(mapping)} / {len(all_names)}")
print(f"  Still unmatched: {len(still_unmatched)}")
if still_unmatched:
    for n in still_unmatched:
        print(f"    {n}  tickers={company_tickers[n]}")

# ── Write final mapping CSV ──
OUTPUT = '/home/tearicee/data_collector/nbim/nbim_tw_mapping.csv'
with open(OUTPUT, 'w', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerow(['nbim_name', 'stock_code', 'chinese_short_name', 'eng_abbrev', 'market', 'match_method'])
    for name in sorted(mapping.keys()):
        m = mapping[name]
        writer.writerow([name, m['code'], m['short_name'], m['eng_abbrev'], m['market'], m['match_method']])

print(f"\nMapping saved to {OUTPUT}")
