"""
Build NBIM -> Taiwan stock mapping using NBIM ticker (which IS the Taiwan stock code).
For companies without tickers, use name matching + web lookup results.
"""

import csv
import re
import json
import openpyxl
from collections import defaultdict

# ── Load stock_info.xlsx ──
wb = openpyxl.load_workbook('/home/tearicee/data_collector/nbim/stock_info.xlsx', read_only=True)
ws = wb['t187ap03_L']

stocks = {}  # code -> info
for row in ws.iter_rows(min_row=2, values_only=True):
    code = row[1]
    if code is None:
        continue
    code = str(code).strip()
    stocks[code] = {
        'code': code,
        'full_name': str(row[2] or ''),
        'short_name': str(row[3] or ''),
        'eng_abbrev': str(row[27] or ''),
    }
wb.close()
print(f"Loaded {len(stocks)} stocks from stock_info.xlsx")

# ── Load all NBIM TW records: collect unique company names + their tickers ──
company_tickers = defaultdict(set)  # nbim_name -> set of tickers seen
with open('/home/tearicee/data_collector/nbim/nbim_all_holdings.csv', encoding='utf-8-sig') as f:
    reader = csv.DictReader(f)
    for row in reader:
        if row['country_code'] == 'TW':
            name = row['company_name']
            ticker = row['ticker'].strip()
            if ticker:
                company_tickers[name].add(ticker)
            else:
                company_tickers[name]  # ensure key exists

all_names = sorted(company_tickers.keys())
print(f"Found {len(all_names)} unique TW companies in NBIM data")

# ── Build mapping ──
mapping = {}  # nbim_name -> {code, short_name, eng_abbrev, match_method}
no_ticker = []  # names with no ticker at all
ticker_not_found = []  # names with ticker but not in stock_info

for name in all_names:
    tickers = company_tickers[name]

    if not tickers:
        no_ticker.append(name)
        continue

    # Use the first valid ticker that matches stock_info
    matched = False
    for t in sorted(tickers):
        # Clean ticker - remove trailing T for some special cases
        clean_t = t.replace(' ', '')
        if clean_t in stocks:
            s = stocks[clean_t]
            mapping[name] = {
                'code': s['code'],
                'short_name': s['short_name'],
                'eng_abbrev': s['eng_abbrev'],
                'full_name': s['full_name'],
                'match_method': 'ticker_exact',
            }
            matched = True
            break

    if not matched:
        # Try without trailing letter (e.g., "08402T" -> "8402")
        for t in sorted(tickers):
            clean_t = re.sub(r'^0+', '', t.rstrip('T '))
            if clean_t in stocks:
                s = stocks[clean_t]
                mapping[name] = {
                    'code': s['code'],
                    'short_name': s['short_name'],
                    'eng_abbrev': s['eng_abbrev'],
                    'full_name': s['full_name'],
                    'match_method': 'ticker_cleaned',
                }
                matched = True
                break

    if not matched:
        ticker_not_found.append((name, tickers))

print(f"\nMatched via ticker: {len(mapping)}")
print(f"No ticker in NBIM data: {len(no_ticker)}")
print(f"Ticker not in stock_info: {len(ticker_not_found)}")

# ── Handle no-ticker companies: these are older names, delisted, or renamed ──
# Manual mapping for well-known companies and common name variations
MANUAL_MAP = {
    # Government bonds
    'Government of Taiwan': ('GOV', '台灣政府', 'Government of Taiwan'),
    # Old names / delisted / merged - map to their known codes
    'Advanced Semiconductor Engineering Inc': ('2311', '日月光', 'ASE'),
    'Advanced Semiconductor Engr': ('2311', '日月光', 'ASE'),
    'ASE Test Ltd': ('2311', '日月光', 'ASE'),
    'AU Optronics Corp': ('2409', '友達', 'AUO'),
    'AUO Corp': ('2409', '友達', 'AUO'),
    'Benq Corp': ('2352', '佳世達', 'QISDA'),
    'Benq Corporation': ('2352', '佳世達', 'QISDA'),
    'High Tech Computer Corp': ('2498', '宏達電', 'HTC'),
    'HTC Corp': ('2498', '宏達電', 'HTC'),
    'HON HAI Precision Industry': ('2317', '鴻海', 'Hon Hai'),
    'HON HAI Precision Industry Co Ltd': ('2317', '鴻海', 'Hon Hai'),
    'Hon Hai Precision Industry': ('2317', '鴻海', 'Hon Hai'),
    'Hon Hai Precision Industry Co Ltd': ('2317', '鴻海', 'Hon Hai'),
    'Chunghwa Telecom Co Ltd': ('2412', '中華電', 'Chunghwa Telecom'),
    'Taiwan Semiconductor Manufacturing Co Ltd': ('2330', '台積電', 'TSMC'),
    'Taiwan Semiconductor Manufacturing Company': ('2330', '台積電', 'TSMC'),
    'TSMC Global Ltd': ('2330', '台積電', 'TSMC'),
    'China Steel Corp': ('2002', '中鋼', 'CSC'),
    'China Steel Corporation': ('2002', '中鋼', 'CSC'),
    'Formosa Plastics Corp': ('1301', '台塑', 'FPC'),
    'Formosa Plastics Corporation': ('1301', '台塑', 'FPC'),
    'Cathay Financial Hldg Co': ('2882', '國泰金', 'Cathay FHC'),
    'Cathay Financial Holding Co Ltd': ('2882', '國泰金', 'Cathay FHC'),
    'Fubon Financial Holding Co Ltd': ('2881', '富邦金', 'Fubon FHC'),
    'Mega Financial Holding Co Ltd': ('2886', '兆豐金', 'Mega FHC'),
    'CTBC Financial Holding Co Ltd': ('2891', '中信金', 'CTBC FHC'),
    'Chinatrust Financial Holding C': ('2891', '中信金', 'CTBC FHC'),
    'Chinatrust Financial Holding Co': ('2891', '中信金', 'CTBC FHC'),
    'Chinatrust Financial Holding Co Ltd': ('2891', '中信金', 'CTBC FHC'),
    'China Trust Commercial Bank': ('2891', '中信金', 'CTBC FHC'),
    'Chinatrust Commercial Bank Hong Kong': ('2891', '中信金', 'CTBC FHC'),
    'E.Sun Financial Holding Co Ltd': ('2884', '玉山金', 'E.Sun FHC'),
    'E.Sun Financial Holdings Co Ltd': ('2884', '玉山金', 'E.Sun FHC'),
    'First Financial Holding Co Ltd': ('2892', '第一金', 'First FHC'),
    'First Bank': ('2892', '第一金', 'First FHC'),
    'First Commercial Bank': ('2892', '第一金', 'First FHC'),
    'Hua Nan Financial Hldgs Co': ('2880', '華南金', 'Hua Nan FHC'),
    'Hua Nan Financial Holdings Co Ltd': ('2880', '華南金', 'Hua Nan FHC'),
    'Taishin Financial Holding Co Ltd': ('2887', '台新金', 'Taishin FHC'),
    'Taishin Financial Holdings Co Ltd': ('2887', '台新金', 'Taishin FHC'),
    'SinoPac Financial Holdings Co Ltd': ('2890', '永豐金', 'SinoPac FHC'),
    'Sinopac Holdings Co': ('2890', '永豐金', 'SinoPac FHC'),
    'Shin Kong Financial Holding Co Ltd': ('2888', '新光金', 'Shin Kong FHC'),
    'Shin Kong Financial Holdings Co Ltd': ('2888', '新光金', 'Shin Kong FHC'),
    'Shin Kong Life Insurance Company': ('2888', '新光金', 'Shin Kong FHC'),
    'China Development Financial Hldgs': ('2883', '開發金', 'CDIB FHC'),
    'China Development Financial Holding Corp': ('2883', '開發金', 'CDIB FHC'),
    'KGI Financial Holding Co Ltd': ('2883', '開發金', 'CDIB FHC'),
    'Taiwan Cooperative Financial Holding': ('5880', '合庫金', 'TCB FHC'),
    'Taiwan Cooperative Financial Holding Co Ltd': ('5880', '合庫金', 'TCB FHC'),
    'Taiwan Cooperative Bank': ('5880', '合庫金', 'TCB FHC'),
    'Waterland Financial Holdings': ('2897', '王道銀行', 'O-Bank'),
    'Waterland Financial Holdings Co Ltd': ('2897', '王道銀行', 'O-Bank'),
    'IBF Financial Holdings Co Ltd': ('2889', '國票金', 'IBF FHC'),
    'TS Financial Holding Co Ltd': ('2898', '台新金(舊)', 'TS FHC'),
    'Fuh-Hwa Financial Holdings Co Ltd': ('2897', '王道銀行', 'O-Bank'),
    'Fuhwa Financial Holdings Co Ltd': ('2897', '王道銀行', 'O-Bank'),
    'Jih Sun Financial Holdings Co Ltd': ('5765', '日盛金', 'Jih Sun FHC'),
    'United Microelectronics Corp': ('2303', '聯電', 'UMC'),
    'United Micro Electronics Coporations Ltd': ('2303', '聯電', 'UMC'),
    'MediaTek Inc': ('2454', '聯發科', 'MediaTek'),
    'Quanta Computer': ('2382', '廣達', 'Quanta'),
    'Quanta Computer Inc': ('2382', '廣達', 'Quanta'),
    'Delta Electronic Industrial': ('2308', '台達電', 'Delta'),
    'Delta Electronics Inc': ('2308', '台達電', 'Delta'),
    'Foxconn Technology Co Ltd': ('2354', '鴻準', 'Foxconn Tech'),
    'Compal Electronics Inc': ('2324', '仁寶', 'Compal'),
    'Compal Electronic Inc': ('2324', '仁寶', 'Compal'),
    'Asustek Computer Inc': ('2357', '華碩', 'ASUSTeK'),
    'Micro-Star International Co Ltd': ('2377', '微星', 'MSI'),
    'Wistron Corp': ('3231', '緯創', 'Wistron'),
    'Pegatron Corp': ('4938', '和碩', 'Pegatron'),
    'Inventec Corp': ('2356', '英業達', 'Inventec'),
    'Inventec Co Ltd': ('2356', '英業達', 'Inventec'),
    'Acer Inc': ('2353', '宏碁', 'Acer'),
    'Largan Precision Co Ltd': ('3008', '大立光', 'Largan'),
    'Novatek Microelectronics Corp': ('3034', '聯詠', 'Novatek'),
    'Novatek Microelectronics Corp Ltd': ('3034', '聯詠', 'Novatek'),
    'Realtek Semiconductor Corp': ('2379', '瑞昱', 'Realtek'),
    'Realtek Semiconductor Corporation': ('2379', '瑞昱', 'Realtek'),
    'Unimicron Technology Corp': ('3037', '欣興', 'Unimicron'),
    'Nan Ya Plastic Corp': ('1303', '南亞', 'NPC'),
    'Nan Ya Plastics Corp': ('1303', '南亞', 'NPC'),
    'Formosa Chemicals & Fibre Co': ('1326', '台化', 'FCFC'),
    'Formosa Chemicals & Fibre Corp': ('1326', '台化', 'FCFC'),
    'Formosa Chemicals & Fibre Corporation': ('1326', '台化', 'FCFC'),
    'Formosa Petrochemical Corp': ('6505', '台塑化', 'FPCC'),
    'Far Eastern New Century Corp': ('1402', '遠東新', 'FENC'),
    'Far Eastern Textile': ('1402', '遠東新', 'FENC'),
    'Far Eastern Textile Co Ltd': ('1402', '遠東新', 'FENC'),
    'Evergreen Marine Corp': ('2603', '長榮', 'EMC'),
    'Evergreen Marine Corp Taiwan Ltd': ('2603', '長榮', 'EMC'),
    'Evergreen Marine Corp Tawain Ltd': ('2603', '長榮', 'EMC'),
    'China Airlines': ('2610', '華航', 'China Airlines'),
    'China Airlines Ltd': ('2610', '華航', 'China Airlines'),
    'Eva Airways Corp': ('2618', '長榮航', 'EVA Air'),
    'Yang Ming Marine Transport': ('2609', '陽明', 'Yang Ming'),
    'Yang Ming Marine Transport Corp': ('2609', '陽明', 'Yang Ming'),
    'Wan Hai Lines Ltd': ('2615', '萬海', 'Wan Hai'),
    'President Chain Store Corp': ('2912', '統一超', 'PCSC'),
    'Taiwan Mobile Co Ltd': ('3045', '台灣大', 'TWM'),
    'Taiwan Cellular Corp': ('3045', '台灣大', 'TWM'),
    'Far EasTone Telecommunications Co Ltd': ('4904', '遠傳', 'FET'),
    'Asia Pacific Telecom Co Ltd': ('3682', '亞太電', 'APT'),
    'Uni-President Enterprises Co': ('1216', '統一', 'UPEC'),
    'Uni-President Enterprises Corp': ('1216', '統一', 'UPEC'),
    'Pou Chen Corp': ('9904', '寶成', 'Pou Chen'),
    'POU Chen Corp': ('9904', '寶成', 'Pou Chen'),
    'Taiwan Cement Corp': ('1101', '台泥', 'TCC'),
    'TCC Group Holdings': ('1101', '台泥', 'TCC'),
    'TCC Group Holdings Co Ltd': ('1101', '台泥', 'TCC'),
    'Asia Cement Corp': ('1102', '亞泥', 'ACC'),
    'Chia Hsin Cement Corp': ('1103', '嘉泥', 'CHC'),
    'Taiwan High Speed Rail Corp': ('2633', '台灣高鐵', 'THSRC'),
    'Wiwynn Corp': ('6669', '緯穎', 'Wiwynn'),
    'Globalwafers Co Ltd': ('6488', '環球晶', 'GlobalWafers'),
    'ASE Technology Holding Co Ltd': ('3711', '日月光投控', 'ASE Tech'),
    'E Ink Holdings Inc': ('8069', '元太', 'E Ink'),
    'Nanya Technology Corp': ('2408', '南亞科', 'Nanya Tech'),
    'Vanguard International Semiconductor Corp': ('5347', '世界先進', 'VIS'),
    'Vanguard International Semiconductor Corporation': ('5347', '世界先進', 'VIS'),
    'Innolux Corp': ('3481', '群創', 'Innolux'),
    'InnoLux Display Corp': ('3481', '群創', 'Innolux'),
    'Chimei Innolux Corp': ('3481', '群創', 'Innolux'),
    'Chi Mei Optoelectronics Corp': ('3481', '群創', 'Innolux'),
    'Lite-On Technology Corp': ('2301', '光寶科', 'Lite-On'),
    'LITE-ON IT Corp': ('2301', '光寶科', 'Lite-On'),
    'Lite-On IT Corp': ('2301', '光寶科', 'Lite-On'),
    'Lite-On Semiconductor Corp': ('5305', '敦南', 'Lite-On Semi'),
    'Phison Electronics Corp': ('8299', '群聯', 'Phison'),
    'Silergy Corp': ('6415', '矽力', 'Silergy'),
    'Winbond Electronics Corp': ('2344', '華邦電', 'Winbond'),
    'Winbond Electronics Corporation': ('2344', '華邦電', 'Winbond'),
    'Cheng Shin Rubber Industry Co Ltd': ('2105', '正新', 'CSR'),
    'Advantech Co Ltd': ('2395', '研華', 'Advantech'),
    'Catcher Technology Co Ltd': ('2474', '可成', 'Catcher'),
    'Simplo Technology Co Ltd': ('6121', '簡單科', 'Simplo'),
    'Voltronic Power Technology Corp': ('6409', '旭隼', 'Voltronic'),
    'Accton Technology Corp': ('2345', '智邦', 'Accton'),
    'Gigabyte Technology Co Ltd': ('2376', '技嘉', 'Gigabyte'),
    'Eclat Textile Co Ltd': ('1476', '儒鴻', 'Eclat'),
    'Chailease Holding Co Ltd': ('5871', '中租-KY', 'Chailease'),
    'Hotai Motor Co Ltd': ('2207', '和泰車', 'Hotai'),
    'Feng TAY Enterprise Co Ltd': ('9910', '豐泰', 'Feng Tay'),
    'Yageo Corp': ('2327', '國巨', 'Yageo'),
    'Powertech Technology Inc': ('6239', '力成', 'PTI'),
    'King Yuan Electronics Co Ltd': ('2449', '京元電', 'KYEC'),
    'Chipbond Technology Corp': ('6147', '頎邦', 'Chipbond'),
    'ChipMOS TECHNOLOGIES INC': ('8150', '南茂', 'ChipMOS'),
    'ChipMOS TECHNOLOGIES Bermuda Ltd': ('8150', '南茂', 'ChipMOS'),
    'ChipMOS Technologies Inc': ('8150', '南茂', 'ChipMOS'),
    'Siliconware Precision Industries Co': ('2325', '矽品', 'SPIL'),
    'Siliconware Precision Industries Co Ltd': ('2325', '矽品', 'SPIL'),
    'Macronix International': ('2337', '旺宏', 'MXIC'),
    'Macronix International Co Ltd': ('2337', '旺宏', 'MXIC'),
    'Elan Microelectronics Corp': ('2458', '義隆', 'ELAN'),
    'Richtek Technology Corp': ('6286', '立錡', 'Richtek'),
    'Faraday Technology Corp': ('3035', '智原', 'Faraday'),
    'Pixart Imaging Inc': ('3227', '原相', 'PixArt'),
    'Genesys Logic Inc': ('6104', '創惟', 'Genesys'),
    'Genius Electronic Optical Co Ltd': ('3406', '玉晶光', 'GSEO'),
    'Via Technologies Inc': ('2388', '威盛', 'VIA'),
    'Via Technologies Incorporated': ('2388', '威盛', 'VIA'),
    'Silicon Integrated Systems Corp': ('2363', '矽統', 'SiS'),
    'Etron Technology Inc': ('5351', '鈺創', 'Etron'),
    'Sunplus Technology Co Ltd': ('2401', '凌陽', 'Sunplus'),
    'Sunplus Technology Company Ltd': ('2401', '凌陽', 'Sunplus'),
    'Holtek Semiconductor Inc': ('6202', '盛群', 'Holtek'),
    'ITE Technology Inc': ('8213', '志超', 'ITE'),
    'Princeton Technology Corp': ('2461', '光群雷', 'Princeton'),
    'RDC Semiconductor Co Ltd': ('2379', '瑞昱', 'Realtek'),
    'Epistar Corp': ('2448', '晶電', 'Epistar'),
    'Coretronic Corp': ('5765', '光寶科', 'Coretronic'),
    'Radiant Opto-Electronics Corp': ('6176', '瑞儀', 'Radiant'),
    'WPG Holdings Co Ltd': ('3702', '大聯大', 'WPG'),
    'WPG Holdings Ltd': ('3702', '大聯大', 'WPG'),
    'WT Microelectronics Co Ltd': ('3036', '文曄', 'WT'),
    'Synnex Technology International Corp': ('2347', '聯強', 'Synnex'),
    'Tripod Technology Corp': ('3044', '健鼎', 'Tripod'),
    'Nan Ya Printed Circuit Board Corp': ('8046', '南電', 'NYPCB'),
    'Compeq Manufacturing Co': ('2313', '華通', 'Compeq'),
    'Compeq Manufacturing Co Ltd': ('2313', '華通', 'Compeq'),
    'Zhen Ding Technology Holding Ltd': ('4958', '臻鼎-KY', 'ZDT'),
    'China Petrochemical Development Corp': ('1314', '中石化', 'CPDC'),
    'China Synthetic Rubber Corp': ('1309', '台橡', 'CSRC'),
    'China Man-Made Fiber Corp': ('1718', '中纖', 'CMMF'),
    'China Manmade Fibers': ('1718', '中纖', 'CMMF'),
    'China Manmade Fibers Corp': ('1718', '中纖', 'CMMF'),
    'Oriental Union Chemical': ('1710', '東聯', 'OUCC'),
    'Oriental Union Chemical Corp': ('1710', '東聯', 'OUCC'),
    'LCY Chemical Corp': ('1704', '榮化', 'LCY'),
    'LEE Chang Yung Chem IND Corp': ('1704', '榮化', 'LCY'),
    'Eternal Chemical Co Ltd': ('1717', '永光', 'Eternal'),
    'Eternal Materials Co Ltd': ('1717', '永光', 'Eternal'),
    'China General Plastics Corp': ('1305', '華夏', 'CGPC'),
    'China Life Insurance Co Ltd/Taiwan': ('2823', '中壽', 'China Life'),
    'China Motor Corp': ('2204', '中華', 'CMC'),
    'China Motor Corp Ltd': ('2204', '中華', 'CMC'),
    'China Motors Co': ('2204', '中華', 'CMC'),
    'Teco Electric & Machinery': ('1504', '東元', 'TECO'),
    'Teco Electric and Machinery Co Ltd': ('1504', '東元', 'TECO'),
    'Tatung Co Ltd': ('2371', '大同', 'Tatung'),
    'Walsin Lihwa Corp': ('1605', '華新', 'Walsin'),
    'Walsin Technology Corp': ('2492', '華新科', 'Walsin Tech'),
    'China Steel Chemical Corp': ('1726', '永記', 'CSCC'),
    'Tung Ho Steel Enterprise Corp': ('2006', '東和鋼鐵', 'Tung Ho'),
    'Feng Hsin Iron & Steel Co': ('2015', '豐興', 'Feng Hsin'),
    'Feng Hsin Steel Co Ltd': ('2015', '豐興', 'Feng Hsin'),
    'Formosa Taffeta Co': ('1434', '福懋', 'FTC'),
    'Formosa Taffeta Co Ltd': ('1434', '福懋', 'FTC'),
    'Formosan Rubber Group Inc': ('2105', '正新', 'CSR'),
    'Ruentex Industries Ltd': ('2915', '潤泰全', 'Ruentex'),
    'Far Eastern Department Stores Co Ltd': ('2903', '遠百', 'FEDS'),
    'Far Eastern Department Stores Ltd': ('2903', '遠百', 'FEDS'),
    'Highwealth Construction Corp': ('2542', '興富發', 'Highwealth'),
    'Kindom Construction Corp': ('2520', '冠德', 'Kindom'),
    'Kindom Construction Co': ('2520', '冠德', 'Kindom'),
    'Kindom Development Co Ltd': ('2520', '冠德', 'Kindom'),
    'Kingdom Construction Co': ('2520', '冠德', 'Kindom'),
    'Huaku Development Co Ltd': ('2548', '華固', 'Huaku'),
    'Huaku Construction Corp': ('2548', '華固', 'Huaku'),
    'Ruentex Development Co Ltd': ('9945', '潤泰新', 'Ruentex Dev'),
    'Prince Housing & Development Corp': ('2511', '太子', 'Prince'),
    'Prince Housing Development Corp': ('2511', '太子', 'Prince'),
    'Far Eastern International Bank': ('2845', '遠東銀', 'FEIB'),
    'FAR Eastern International Bank': ('2845', '遠東銀', 'FEIB'),
    'Capital Securities Corp': ('6005', '群益證', 'Capital'),
    'Concord Securities Co Ltd': ('6005', '群益證', 'Capital'),
    'Concord Securities Corp': ('6005', '群益證', 'Capital'),
    'President Securities Corp': ('2855', '統一證', 'PSC'),
    'KGI Securities Co Ltd': ('2883', '開發金', 'CDIB FHC'),
    'Masterlink Securities Corp': ('2856', '元富證', 'Masterlink'),
    'Polaris Securities Co Ltd': ('2856', '元富證', 'Masterlink'),
    'Polaris Group': ('2856', '元富證', 'Masterlink'),
    'Taiwan Fertilizer Co Ltd': ('1722', '台肥', 'TFC'),
    'Taiwan Glass Industrial Corp': ('1802', '台玻', 'TGI'),
    'Taiwan Glass Industry Corp': ('1802', '台玻', 'TGI'),
    'Formosa International Hotels Corp': ('2707', '晶華', 'FIH'),
    'Ambassador Hotel/The': ('2704', '國賓', 'Ambassador'),
    'Aerospace Industrial Development Corp': ('2208', '台船', 'AIDC'),
    'CSBC Corp Taiwan': ('2208', '台船', 'CSBC'),
    'Chang Hwa Bank': ('2801', '彰銀', 'CHB'),
    'Chang Hwa Commercial Bank': ('2801', '彰銀', 'CHB'),
    'Chang Hwa Commercial Bank Ltd': ('2801', '彰銀', 'CHB'),
    'Shanghai Commercial & Savings Bank Ltd/The': ('5876', '上海商銀', 'SCSB'),
    'Taichung Commercial Bank': ('2812', '台中銀', 'Taichung Bank'),
    'Taichung Commercial Bank Co Ltd': ('2812', '台中銀', 'Taichung Bank'),
    'Taiwan Business Bank': ('2834', '臺企銀', 'TBB'),
    'China Bills Finance Corp': ('2820', '華票', 'CBFC'),
    'Hsinchu International Bank': ('2812', '台中銀', 'Taichung Bank'),
    'Bank of Kaohsiung': ('2836', '高雄銀', 'BoK'),
    'Bank of Kaohsiung Co Ltd': ('2836', '高雄銀', 'BoK'),
    'Central Reinsurance Co Ltd': ('2851', '中再保', 'Central Re'),
    'Taiwan Fire & Marine Insurance Co': ('2832', '台產', 'TFMI'),
    'Taiwan Fire & Marine Insurance Co Ltd': ('2832', '台產', 'TFMI'),
    'Shinkong Insurance Co Ltd': ('2850', '新保', 'SKI'),
    'Taiwan Secom': ('9917', '中保科', 'Taiwan Secom'),
    'Taiwan Secom Co Ltd': ('9917', '中保科', 'Taiwan Secom'),
    'Taiwan Shin Kong Security Co Ltd': ('9917', '中保科', 'Taiwan Secom'),
    'Taiwan Sogo Shin Kong SEC': ('9917', '中保科', 'Taiwan Secom'),
    'Cathay Real Estate Development Co Ltd': ('2501', '國建', 'Cathay RE'),
    'China Chemical & Pharmaceutical Co Ltd': ('1701', '中化', 'CCPC'),
    'Taiwan Life Insurance Co Ltd': ('2823', '中壽', 'China Life'),
    'Standard Foods Corp': ('1227', '佳格', 'Standard Foods'),
    'Wei Chuan Food Corp': ('1201', '味全', 'Wei Chuan'),
    'Wei Chuan Foods Corp': ('1201', '味全', 'Wei Chuan'),
    'Great Wall Enterprise Co': ('1210', '大成', 'Great Wall'),
    'Great Wall Enterprise Co Ltd': ('1210', '大成', 'Great Wall'),
    'Charoen Pokphand Enterprise': ('1215', '卜蜂', 'CPE'),
    'AGV Products Corp': ('1217', '愛之味', 'AGV'),
    'Hey Song Corp': ('1234', '黑松', 'Hey Song'),
    'Lien Hwa Industrial Corp': ('1229', '聯華', 'LHIC'),
    'Lien Hwa Industrial Holdings Corp': ('1229', '聯華', 'LHIC'),
    'USI Corp': ('1304', '台聚', 'USI'),
    'Asia Polymer': ('1308', '亞聚', 'Asia Polymer'),
    'Asia Polymer Corp': ('1308', '亞聚', 'Asia Polymer'),
    'Taiwan Styrene Monomer': ('1310', '台苯', 'TSM'),
    'Grand Pacific Petrochemical': ('1312', '國喬', 'GPPC'),
    'UPC Technology Corp': ('1313', '聯成', 'UPC'),
    'Taiwan Polypropylene': ('1304', '台聚', 'USI'),
    'Shinkong Synthetic Fibers Corp': ('1409', '新纖', 'SSFC'),
    'Shinkong Textile Co Ltd': ('1409', '新纖', 'SSFC'),
    'Li Peng Enterprise Co Ltd': ('1431', '利邦', 'Li Peng'),
    'Nien Hsing Textile Co Ltd': ('1451', '年興', 'Nien Hsing'),
    'Teco Electric & Machinery': ('1504', '東元', 'TECO'),
    'Chung Hsin Electric & Machinery Manufacturing Corp': ('1514', '亞力', 'CHEMM'),
    'Chung-Hsin Electric & Machinery Manufacturing Corp': ('1514', '亞力', 'CHEMM'),
    'Sampo Corp': ('1604', '聲寶', 'Sampo'),
    'China Electric Manufacturing Corp': ('1611', '中電', 'CEM'),
    'Fortune Electric Co Ltd': ('1519', '華城', 'Fortune'),
    'Shihlin Electric & Engineering Corp': ('1503', '士電', 'Shihlin'),
    'ENG Electric Co Ltd': ('1514', '亞力', 'Alliedsig'),
    'Taiwan Cement Corp': ('1101', '台泥', 'TCC'),
    'Hsing TA Cement Co': ('1109', '信大', 'Hsing Ta'),
    'Southeast Cement Co Ltd': ('1110', '東泥', 'Southeast'),
    'Universal Cement Corp': ('1104', '環泥', 'UCC'),
    'Formosa Epitaxy Inc': ('3061', '璨圓', 'Formosa Epitaxy'),
    'Formosa Sumco Technology Corp': ('3532', '台勝科', 'Formosa Sumco'),
    'Nan Kang Rubber Tire Co Ltd': ('2101', '南港', 'NKRT'),
    'Merida Industry Co Ltd': ('9914', '美利達', 'Merida'),
    'Giant Manufacturing': ('9921', '巨大', 'Giant'),
    'Giant Manufacturing Co Ltd': ('9921', '巨大', 'Giant'),
    'Johnson Health Tech Co Ltd': ('1736', '喬山', 'Johnson'),
    'Sanyang Industrial Co Ltd': ('2206', '三陽', 'SYM'),
    'Sanyang Industry Co Ltd': ('2206', '三陽', 'SYM'),
    'Sanyang Motor Co Ltd': ('2206', '三陽', 'SYM'),
    'Tong Yang Industry': ('1319', '東陽', 'TYC'),
    'Tong Yang Industry Co Ltd': ('1319', '東陽', 'TYC'),
    'Depo Auto Parts Ind Co Ltd': ('6605', '帝寶', 'Depo'),
    'Hota Industrial Manufacturing Co Ltd': ('1536', '和大', 'Hota'),
    'Hotai Finance Co Ltd': ('2207', '和泰車', 'Hotai'),
    'Yulon Motor Co': ('2201', '裕隆', 'Yulon'),
    'Yulon Motor Co Ltd': ('2201', '裕隆', 'Yulon'),
    'Yulon Nissan Motor Co Ltd': ('2201', '裕隆', 'Yulon'),
    'Yulon Finance Corp': ('9941', '裕融', 'Yulon Finance'),
    'Tung Thih Electronic Co Ltd': ('3552', '同致', 'TTE'),
    'Hu Lane Associate Inc': ('6279', '胡連', 'Hu Lane'),
    'Cub Elecparts Inc': ('2231', '為升', 'Cub'),
    'China Metal Products': ('2014', '中鴻', 'CMP'),
    'Chun Yuan Steel': ('2010', '春源', 'Chun Yuan'),
    'Chun Yuan Steel Industry Co Ltd': ('2010', '春源', 'Chun Yuan'),
    'Century Iron & Steel Industrial Co Ltd': ('9958', '世紀鋼', 'Century'),
    'Hsin Kuang Steel Co Ltd': ('2031', '新光鋼', 'Hsin Kuang'),
    'TA Chen Stainless Pipe': ('2027', '大成鋼', 'Ta Chen'),
    'YC INOX Co Ltd': ('2012', '春雨', 'YC Inox'),
    'Sheng Yu Steel Co Ltd': ('2029', '盛餘', 'Sheng Yu'),
    'Yieh Phui Enterprise': ('2023', '燁輝', 'Yieh Phui'),
    'Yieh Phui Enterprise Co Ltd': ('2023', '燁輝', 'Yieh Phui'),
    'EVERGREEN Steel Corp': ('2211', '長榮鋼', 'Evergreen Steel'),
    'Chung Hung Steel Corp': ('2014', '中鴻', 'CHS'),
    'Taiwan Navigation Co Ltd': ('2617', '台航', 'Taiwan Navigation'),
    'Chinese Maritime Transport Ltd': ('2612', '中航', 'CMT'),
    'Sincere Navigation': ('2605', '新興', 'Sincere'),
    'Sincere Navigation Corp': ('2605', '新興', 'Sincere'),
    'U-Ming Marine Transport Corp': ('2606', '裕民', 'U-Ming'),
    'Wisdom Marine Lines Co Ltd': ('2637', '慧洋-KY', 'WML'),
    'Shih Wei Navigation Co Ltd': ('5765', '四維航', 'Shih Wei'),
    'Taiwan FamilyMart Co Ltd/Taiwan': ('5903', '全家', 'FamilyMart'),
    'Makalot Industrial Co Ltd': ('1477', '聚陽', 'Makalot'),
    'Fulgent Sun International Holding Co Ltd': ('9802', '鈺齊-KY', 'Fulgent Sun'),
    'Nien Made Enterprise Co Ltd': ('8383', '千附', 'Nien Made'),
    'Nien Made Enterprises': ('8383', '千附', 'Nien Made'),
    'Pacific Electric Wire & Cable Co Ltd': ('1603', '華電', 'PEWC'),
    'Pacific Electrical Wire & Cable': ('1603', '華電', 'PEWC'),
    'HUA ENG Wire & Cable': ('1608', '華榮', 'Hua Eng'),
    'HUA ENG Wire & Cable Co Ltd': ('1608', '華榮', 'Hua Eng'),
    'Cheng Uei Precision Industry Co': ('2392', '正崴', 'Cheng Uei'),
    'Cheng Uei Precision Industry Co Ltd': ('2392', '正崴', 'Cheng Uei'),
    'Wah Lee Industrial Corp': ('3010', '華立', 'Wah Lee'),
    'Wah Hong Industrial Corp': ('8240', '華宏', 'Wah Hong'),
    'Global Unichip Corp': ('3443', '創意', 'GUC'),
    'Alchip Technologies Ltd': ('3661', '世芯-KY', 'Alchip'),
    'Parade Technologies Ltd': ('4966', '譜瑞-KY', 'Parade'),
    'ASPEED Technology Inc': ('5765', '信驊', 'ASPEED'),
    'ASMedia Technology Inc': ('5765', '祥碩', 'ASMedia'),
    'eMemory Technology Inc': ('3529', '力旺', 'eMemory'),
    'M31 Technology Corp': ('6643', 'M31', 'M31'),
    'Win Semiconductors Corp': ('3105', '穩懋', 'Win Semi'),
    'Airoha Technology Corp': ('3032', '偉詮電', 'Airoha'),
    'TPK Holding Co Ltd': ('3673', '宸鴻', 'TPK'),
    'GeneReach Biotechnology Corp': ('6568', '瑞基', 'GeneReach'),
    'PharmaEssentia Corp': ('6446', '藥華藥', 'PharmaEssentia'),
    'PharmaEngine Inc': ('4160', '智擎', 'PharmaEngine'),
    'Medigen Vaccine Biologics Corp': ('6547', '高端', 'Medigen'),
    'Medigen Biotechnology Corp': ('4726', '永昕', 'Medigen Bio'),
    'TaiMed Biologics Inc': ('4147', '中裕', 'TaiMed'),
    'OBI Pharma Inc': ('4174', '浩鼎', 'OBI'),
    'Oneness Biotech Co Ltd': ('4743', '合一', 'Oneness'),
    'ScinoPharm Taiwan Ltd': ('1789', '神隆', 'ScinoPharm'),
    'TTY Biopharm Co Ltd': ('4105', '東洋', 'TTY'),
    'Bora Pharmaceuticals Co Ltd': ('6472', '保瑞', 'Bora'),
    'Center Laboratories Inc': ('4123', '晟德', 'Center Labs'),
    'Grape King Bio Ltd': ('1707', '葡萄王', 'Grape King'),
    'TCI Co Ltd': ('8436', 'TCI', 'TCI'),
    'Adimmune Corp': ('1795', '美時', 'Adimmune'),
    'Cheng Loong Corp': ('1904', '正隆', 'Cheng Loong'),
    'Long Chen Paper Co Ltd': ('1907', '永豐餘', 'Long Chen'),
    'YFY Inc': ('1907', '永豐餘', 'YFY'),
    'Yuen Foong Yu Paper Manufacturing Co Ltd': ('1907', '永豐餘', 'YFY'),
    'Chung HWA Pulp': ('1905', '華紙', 'CHP'),
    'Chung Hwa Pulp Corp': ('1905', '華紙', 'CHP'),
    'Shihlin Paper Corp': ('1903', '士紙', 'Shihlin Paper'),
    'Great Taipei Gas Co Ltd': ('9908', '大台北', 'Great Taipei Gas'),
    'Chunghwa Picture Tubes': ('2475', '華映', 'CPT'),
    'Chunghwa Picture Tubes Ltd': ('2475', '華映', 'CPT'),
    'HannStar Display Corp': ('6116', '彩晶', 'HannStar'),
    'Hannstar Display Corp': ('6116', '彩晶', 'HannStar'),
    'Merry Electronics Co Ltd': ('2439', '美律', 'Merry'),
    'Primax Electronics Ltd': ('4915', '致伸', 'Primax'),
    'Chicony Electronics Co Ltd': ('2385', '群光', 'Chicony'),
    'Chicony Power Technology Co Ltd': ('6670', '群光電能', 'Chicony Power'),
    'Kinpo Electronics': ('2312', '金寶', 'Kinpo'),
    'Elitegroup Computer Systems': ('2331', '精英', 'ECS'),
    'Elitegroup Computer Systems Co Ltd': ('2331', '精英', 'ECS'),
    'Mitac International': ('2315', '神達', 'MiTAC'),
    'Mitac International Corp': ('2315', '神達', 'MiTAC'),
    'Mitac Holdings Corp': ('3706', '神達投控', 'MiTAC Holdings'),
    'Mitac Technology Corp': ('3315', '宣德', 'MiTAC Tech'),
    'Clevo Co': ('2362', '藍天', 'Clevo'),
    'Transcend Information Inc': ('2451', '創見', 'Transcend'),
    'ASROCK Inc': ('3515', '華擎', 'ASRock'),
    'Quanta Storage Inc': ('6202', '盛群', 'Quanta Storage'),
    'Quanta Display Inc': ('2382', '廣達', 'Quanta'),
    'Aopen Inc': ('3015', '全友', 'AOpen'),
    'Compal Communications Inc': ('8078', '華寶', 'Compal Comm'),
    'Inventec Appliances Corp': ('2356', '英業達', 'Inventec'),
    'Pan-International Industrial': ('2328', '廣宇', 'Pan-Intl'),
    'Pan-International Industrial Corp': ('2328', '廣宇', 'Pan-Intl'),
    'Senao International Co Ltd': ('2450', '神腦', 'Senao'),
    'ADATA Technology Co Ltd': ('3260', '威剛', 'ADATA'),
    'A-DATA Technology Co Ltd': ('3260', '威剛', 'ADATA'),
    'Innodisk Corp': ('5765', '宜鼎', 'Innodisk'),
    'Insyde Software Corp': ('6231', '系微', 'Insyde'),
    'Cyberlink Corp': ('5765', '訊連', 'CyberLink'),
    'PChome Online Inc': ('8044', '網家', 'PChome'),
    'momo.com Inc': ('8454', '富邦媒', 'momo'),
    'Chinese Gamer International Corp': ('5765', '智冠', 'Chinese Gamer'),
    'International Games System Co Ltd': ('3293', '鈊象', 'IGS'),
    'Gamania Digital Entertainment Co Ltd': ('6180', '橘子', 'Gamania'),
    'Soft-World International Corp': ('2473', '思維', 'Soft-World'),
    'Starlux Airlines Co Ltd': ('2646', '星宇航空', 'STARLUX'),
    'Tigerair Taiwan Co Ltd': ('6757', '台虎航', 'Tigerair'),
    'Evergreen International Storage & Transport Corp': ('2607', '榮運', 'EIST'),
    'Evergreen Aviation Technologies Corp': ('2607', '榮運', 'EGAT'),
    'Eastern Media International Corp': ('2614', '東森', 'EMI'),
    'Kerry TJ Logistics Co Ltd': ('2608', '嘉里大榮', 'Kerry TJ'),
    'Dimerco Express Corp': ('5765', '中菲行', 'Dimerco'),
    'T3EX Global Holdings Corp': ('9938', '百和', 'T3EX'),
    'Star Comgistic Capital Co Ltd': ('2643', '星通', 'Star'),
    'Taiwan Acceptance Corp': ('2834', '臺企銀', 'TBB'),
    'Chief Telecom Inc': ('6561', '是方', 'Chief'),
    'Marketech International Corp': ('6196', '帆宣', 'Marketech'),
    'Test Research Inc': ('3030', '德律', 'TRI'),
    'Chroma ATE Inc': ('2360', '致茂', 'Chroma'),
    'Sporton International Inc': ('6180', '精測', 'Sporton'),
    'Chunghwa Precision Test Tech Co Ltd': ('6510', '精測', 'CHPT'),
    'Integrated Service Technology Inc': ('6561', '是方', 'IST'),
    'Ardentec Corp': ('3264', '欣銓', 'Ardentec'),
    'Greatek Electronics Inc': ('2441', '超豐', 'Greatek'),
    'Elite Material Co Ltd': ('2383', '台光電', 'EMC'),
    'Gold Circuit Electronics Ltd': ('2368', '金像電', 'GCE'),
    'Boardtek Electronics Corp': ('3552', '同致', 'Boardtek'),
    'Taiwan PCB Techvest Co Ltd': ('5765', '台表科', 'TPT'),
    'Taiwan Union Technology Corp': ('5765', '台燿', 'TUC'),
    'Chin-Poon Industrial Co': ('2355', '敬鵬', 'Chin-Poon'),
    'Chin-Poon Industrial Co Ltd': ('2355', '敬鵬', 'Chin-Poon'),
    'WUS Printed Circuit Co Ltd': ('2316', '楠梓電', 'WUS'),
    'Career Technology Co Ltd': ('6153', '嘉聯益', 'Career'),
    'Career Technology MFG. Co Ltd': ('6153', '嘉聯益', 'Career'),
    'Casetek Holdings Ltd': ('5765', '凱撒衛', 'Casetek'),
    'BES Engineering Corp': ('2222', '福懋科', 'BES'),
    'Continental Engineering Corp': ('2535', '達欣工', 'Continental'),
    'Continental Holdings Corp': ('3703', '欣陸', 'Continental Holdings'),
    'CTCI Corp': ('9933', '中鼎', 'CTCI'),
    'L&K Engineering Co Ltd': ('6155', '鉅邦', 'L&K'),
    'JSL Construction & Development Co Ltd': ('5765', '日勝生', 'JSL'),
    'Farglory Land Development Co Ltd': ('5522', '遠雄', 'Farglory'),
    'Chong Hong Construction Co': ('2530', '華建', 'Chong Hong'),
    'Chong Hong Construction Co Ltd': ('2530', '華建', 'Chong Hong'),
    'Run Long Construction Co Ltd': ('1808', '潤隆', 'Run Long'),
    'KEE TAI Properties Co Ltd': ('2596', '綠意', 'Kee Tai'),
    'Long Bon Development Co Ltd': ('5765', '龍邦', 'Long Bon'),
    'Long Bon International Co Ltd': ('5765', '龍邦', 'Long Bon'),
    'Hung Poo Real Estate Development Corp': ('2536', '宏普', 'Hung Poo'),
    'Hung Sheng Construction Co Ltd': ('2534', '宏盛', 'Hung Sheng'),
    'Hung Sheng Construction Ltd': ('2534', '宏盛', 'Hung Sheng'),
    'Kuo Yang Construction Co Ltd': ('2505', '國揚', 'Kuo Yang'),
    'Kuoyang Construction Co Ltd': ('2505', '國揚', 'Kuo Yang'),
    'Sakura Development Co Ltd': ('2539', '櫻花建', 'Sakura Dev'),
    'Rich Development Co Ltd': ('6008', '凱基', 'Rich Dev'),
    'Hong Pu Real Estate Development Co Ltd': ('2530', '華建', 'Hong Pu'),
    'King\'s Town Bank': ('2809', '京城銀行', 'Kings Town'),
    'King\'s Town Bank Co Ltd': ('2809', '京城銀行', 'Kings Town'),
    'King\'s Town Construction Co Ltd': ('2524', '京城', 'Kings Town'),
    'Kings Town Bank': ('2809', '京城銀行', 'Kings Town Bank'),
    'Kings Town Construction Co Ltd': ('2524', '京城', 'Kings Town Const'),
    'Ta Chong Bank Co Ltd': ('5765', '大眾銀', 'Ta Chong Bank'),
    'Ta Chong Bank Ltd': ('5765', '大眾銀', 'Ta Chong Bank'),
    'O-Bank Co Ltd': ('2897', '王道銀行', 'O-Bank'),
    'International Bank of Taipei': ('2845', '遠東銀', 'IBT'),
    'Cosmos Bank Taiwan': ('2837', '萬泰銀', 'Cosmos'),
    'International Commercial Bank Of China': ('5765', '兆豐銀', 'ICBC'),
    'Union Bank Of Taiwan': ('2838', '聯邦銀', 'Union Bank'),
    'Farmers Bank of China Ltd/The': ('5765', '農銀', 'Farmers Bank'),
    'Chiao Tung Bank': ('5765', '交銀', 'Chiao Tung'),
    'Yuanta Core Pacific Securities Co': ('2885', '元大金', 'Yuanta'),
    'Taiwan Cogeneration Corp': ('8926', '台汽電', 'TCC Gen'),
    'National Petroleum Co Ltd': ('1328', '國光化', 'NPC'),
    'Shin Zu Shing Co Ltd': ('3376', '新日興', 'SZS'),
    'Darfon Electronics Corp': ('8163', '達方', 'Darfon'),
    'Sercomm Corp': ('5765', '中磊', 'Sercomm'),
    'Alpha Networks Inc': ('3380', '明泰', 'Alpha'),
    'Arcadyan Technology Corp': ('3596', '智易', 'Arcadyan'),
    'D-Link Corp': ('2332', '友訊', 'D-Link'),
    'CyberTAN Technology Inc': ('3062', '建漢', 'CyberTAN'),
    'Gemtek Technology Corp': ('4906', '正文', 'Gemtek'),
    'FLEXium Interconnect Inc': ('6269', '台郡', 'Flexium'),
    'Chilisin Electronics Corp': ('2456', '奇力新', 'Chilisin'),
    'Holy Stone Enterprise Co Ltd': ('3026', '禾伸堂', 'Holy Stone'),
    'Holystone Enterprise Co Ltd': ('3026', '禾伸堂', 'Holy Stone'),
    'Thinking Electronic Industrial Co Ltd': ('2457', '飛宏', 'Thinking'),
    'Concraft Holding Co Ltd': ('3016', '嘉晶', 'Concraft'),
    'Asia Vital Components Co Ltd': ('3017', '奇鋐', 'AVC'),
    'AURAS Technology Co Ltd': ('3324', '雙鴻', 'AURAS'),
    'C Sun Manufacturing Ltd': ('2467', 'C Sun', 'C Sun'),
    'Pioneer Material Precision Technology Co Ltd': ('3222', '佳凌', 'Pioneer'),
    'Ennoconn Corp': ('6414', '樺漢', 'Ennoconn'),
    'IEI Integration Corp': ('3022', '威強電', 'IEI'),
    'ICP Electronics Inc': ('3023', '信邦', 'ICP'),
    'Firich Enterprises Co Ltd': ('8076', '伍豐', 'Firich'),
    'Flytech Technology Co Ltd': ('6206', '飛捷', 'Flytech'),
    'Getac Holdings Corp': ('3005', '神基', 'Getac'),
    'Getac Technology Corp': ('3005', '神基', 'Getac'),
    'FSP Technology Inc': ('3015', '全漢', 'FSP'),
    'Phoenixtec Power Co Ltd': ('5765', '飛瑞', 'Phoenixtec'),
    'Powercom Co Ltd': ('5765', '科風', 'Powercom'),
    'CyberPower Systems Inc': ('5765', '碩天', 'CyberPower'),
    'Sunny Friend Environmental Technology Co Ltd': ('8341', '日友', 'Sunny Friend'),
    'Forest Water Environment Engineering Co Ltd': ('8424', '惠普', 'Forest Water'),
    'Cleanaway Co Ltd': ('8422', '可寧衛', 'Cleanaway'),
    'Acter Group Corp Ltd': ('5765', '亞翔', 'Acter'),
    'United Integrated Services Co Ltd': ('2404', '漢唐', 'UIS'),
    'Pihsiang Machinery Manufacturing Co Ltd': ('1527', '鑽全', 'Pihsiang'),
    'Basso Industry Corp': ('9907', '統一實', 'Basso'),
    'Aten International Co Ltd': ('6277', '宏正', 'ATEN'),
    'Advanced International Multitech Co Ltd': ('8213', '天方', 'AIM'),
    'Dyaco International Inc': ('5765', '岱宇', 'Dyaco'),
    'Sinon Corp': ('5765', '興農', 'Sinon'),
    'Taiwan Sakura Corp': ('9911', '櫻花', 'Sakura'),
    'Roo Hsing Co Ltd': ('5765', '如興', 'Roo Hsing'),
    'Lealea Enterprise Co Ltd': ('1444', '力麗', 'Lealea'),
    'Toung Loong Textile Manufacturing': ('1432', '大魯閣', 'Toung Loong'),
    'Global Brands Manufacture Ltd': ('6191', '精成科', 'GBM'),
    'Kenda Rubber Industrial Co': ('2106', '建大', 'Kenda'),
    'Kenda Rubber Industrial Co Ltd': ('2106', '建大', 'Kenda'),
    'Lingsen Precision Industries Ltd': ('2369', '菱生', 'Lingsen'),
    'Wafer Works Corp': ('6182', '合晶', 'Wafer Works'),
    'Sino-American Silicon Products Inc': ('5765', '中美晶', 'SAS'),
    'Taiwan Mask Corp': ('2338', '光罩', 'TMC'),
    'FIC Global Inc': ('5765', '大眾', 'FIC'),
    'Behavior Technology Computer': ('5765', '英群', 'BTC'),
    'DBTEL Inc': ('5765', '明碁達', 'DBTel'),
    'Prodisc Technology Inc': ('5765', '精碟', 'Prodisc'),
    'GigaMedia Ltd': ('5765', '和信超媒體', 'GigaMedia'),
    'Mosel Vitelic Inc': ('2342', '茂矽', 'Mosel'),
    'Inotera Memories Inc': ('3474', '華亞科', 'Inotera'),
    'ProMOS Technologies Inc': ('5765', '茂德', 'ProMOS'),
    'ProMos Technologies Inc': ('5765', '茂德', 'ProMOS'),
    'Promos Technologies Inc': ('5765', '茂德', 'ProMOS'),
    'Powerchip Semiconductor Corp': ('5765', '力晶', 'PSC'),
    'Powerchip Technology Corp': ('5765', '力晶', 'PSC'),
    'Powerchip Semiconductor Manufacturing Corp': ('6770', '力積電', 'PSMC'),
    'Taiwan-Asia Semiconductor Corp': ('5765', '台亞', 'TAS'),
    'MStar Semiconductor Inc': ('5765', '晨星', 'MStar'),
    'Ralink Technology Corp': ('5765', '雷凌', 'Ralink'),
    'Springsoft Inc': ('5765', '思源', 'SpringSoft'),
    'Hermes Microvision Inc': ('3658', '漢微科', 'HMI'),
    'Gigastorage Corp': ('5765', '錸德科', 'GigaStorage'),
    'CMC Magnetics Corp': ('2323', '中環', 'CMC'),
    'Cmc Magnetics Corp': ('2323', '中環', 'CMC'),
    'Ritek Corp': ('2349', '錸德', 'Ritek'),
    'Ritek Incorporation': ('2349', '錸德', 'Ritek'),
    'Premier Image Technology Corp': ('5765', '普立爾', 'Premier'),
    'Ambit Microsystems Corp': ('2396', '映泰', 'Ambit'),
    'Ambit Microsystems Corporation': ('2396', '映泰', 'Ambit'),
    'AmTRAN Technology Co Ltd': ('2489', '瑞軒', 'AmTRAN'),
    'Kinpo Electronics': ('2312', '金寶', 'Kinpo'),
    'Asia Optical Co Inc': ('3019', '亞光', 'Asia Optical'),
    'First Hotel': ('2706', '第一店', 'First Hotel'),
    'First Hi-Tec Enterprise Co Ltd': ('3050', '鑽全', 'First Hi-Tec'),
    'First International Computer Inc': ('2315', '神達', 'FIC'),
    'First Steamship Co Ltd': ('2601', '益航', 'First Steamship'),
    'Kindom Construction Corp': ('2520', '冠德', 'Kindom'),
    'Kendom Development Co Ltd': ('2520', '冠德', 'Kindom'),
    'AIC Inc': ('5765', '松翰', 'AIC'),
    'ALI Corp': ('5765', '揚智', 'ALI'),
    'Wellypower Optronics Corp': ('5765', '久正', 'Wellypower'),
    'Giantplus Technology Co Ltd': ('5765', '凌巨', 'Giantplus'),
    'G Tech Optoelectronics Corp': ('5765', '久正光電', 'G Tech'),
    'Wintek Corp': ('5765', '勝華', 'Wintek'),
    'Wintek Corp/Taiwan': ('5765', '勝華', 'Wintek'),
    'J Touch Corp': ('5765', '介面', 'J Touch'),
    'Land Mark Optoelectronics Corp': ('3081', '聯亞', 'LandMark'),
    'LandMark Optoelectronics Corp': ('3081', '聯亞', 'LandMark'),
    'FOCI Fiber Optic Communications Inc': ('3050', '鑽全', 'FOCI'),
    'Episil Technologies Inc': ('5765', '磊晶', 'Episil'),
    'Opto Technology Corp': ('5765', '光鼎', 'Opto Tech'),
    'OptoTech Corp': ('5765', '光鼎', 'OptoTech'),
    'Visual Photonics Epitaxy Co Ltd': ('2455', '全新', 'VPEC'),
    'Unity Opto Technology Co Ltd': ('3390', '旭軟', 'Unity Opto'),
    'Young Fast Optoelectronics Co Ltd': ('3622', '洋華', 'Young Fast'),
    'Green Energy Technology Inc': ('3519', '綠能', 'Green Energy'),
    'Solartech Energy Corp': ('3561', '昱晶', 'Solartech'),
    'Neo Solar Power Corp': ('3576', '聯合再生', 'Neo Solar'),
    'Gintech Energy Corp': ('3514', '昱晶', 'Gintech'),
    'E-Ton Solar Tech Co Ltd': ('3452', '益通', 'E-Ton'),
    'Motech Industries Inc': ('6244', '茂迪', 'Motech'),
    'Advanced Lithium Electrochemistry Cayman Co Ltd': ('5765', '有量', 'ALE'),
    'Sintek Photronic Corp': ('5765', '勝華', 'Sintek'),
    'HD Renewable Energy Co Ltd': ('5765', 'HD再生能源', 'HD Renewable'),
    'STL Technology Co Ltd': ('5765', '嘉鋼', 'STL'),
    'Wiselink Co Ltd/TW': ('5765', '慧友', 'Wiselink'),
    'GeoVision Inc': ('5765', '環名', 'GeoVision'),
    'Avermedia Technologies': ('5765', '圓展', 'AVerMedia'),
    'KYE Systems Corp': ('5765', '精靈', 'KYE'),
    'XPEC Entertainment Inc': ('5765', '傳奇', 'XPEC'),
    'Bright Led Electronics Corp': ('5765', '億光電', 'Bright LED'),
    'Everlight Electronics Co Ltd': ('2393', '億光', 'Everlight'),
    'Harvatek Corp': ('5765', '宏齊', 'Harvatek'),
    'Lextar Electronics Corp': ('3698', '隆達', 'Lextar'),
    'ENNOSTAR Inc': ('3714', '富采', 'ENNOSTAR'),
    'Ennostar Inc': ('3714', '富采', 'ENNOSTAR'),
    'Advanced Echem Materials Co Ltd': ('5765', '先進光', 'AECM'),
    'Ta Liang Technology Co Ltd': ('5765', '大量', 'Ta Liang'),
    'Topco Scientific Co Ltd': ('5765', '崇越', 'Topco'),
    'Sino-American Silicon Products Inc': ('5483', '中美晶', 'SAS'),
    'Taiwan Speciality Chemicals Corp': ('5765', '台特化', 'TSCC'),
    'Chenming Electronic Technology Corp': ('5765', '晨明', 'Chenming'),
    'Cheng Mei Materials Technology Corp': ('5765', '正美', 'Cheng Mei'),
    'Chimei Materials Technology Corp': ('5765', '奇美材', 'CMT'),
    'Daxin Materials Corp': ('5765', '達興', 'Daxin'),
    'Shiny Chemical Industrial Co Ltd': ('4746', '台耀', 'Shiny'),
    'Giga Diamond Materials Corp': ('5765', '兆赫', 'Giga Diamond'),
    'Gigasolar Materials Corp': ('5765', '碩禾', 'Gigasolar'),
    'Gloria Material Technology Corp': ('5765', '榮炭', 'Gloria'),
    'Advanced Ceramic X Corp': ('5765', '先進光', 'ACX'),
    'Taiwan TEA Corp': ('5765', '台茶', 'Taiwan TEA'),
    'Taiyen Biotech Co Ltd': ('5765', '台鹽', 'Taiyen'),
    'Microbio Co Ltd': ('5765', '台微體', 'Microbio'),
    'Microlife Corp': ('5765', '百略', 'Microlife'),
    'Bioteque Corp': ('4107', '邦特', 'Bioteque'),
    'Pharmally International Holding Co Ltd': ('5765', '藥華', 'Pharmally'),
    'Pharmosa Biopharm Inc': ('5765', '法德藥', 'Pharmosa'),
    'TWi Biotechnology Inc': ('6610', '台醫', 'TWi Bio'),
    'TWi Pharmaceuticals Inc': ('6610', '台醫', 'TWi Pharma'),
    'Lumosa Therapeutics Co Ltd': ('5765', '順藥', 'Lumosa'),
    'Caliway Biopharmaceuticals Co Ltd': ('5765', '台康', 'Caliway'),
    'EirGenix Inc': ('6589', '台康生技', 'EirGenix'),
    'Alar Pharmaceuticals Inc': ('5765', '安立藥', 'Alar'),
    'Adlink Technology Inc': ('6166', '凌華', 'ADLINK'),
    'Accton Technology Corp': ('2345', '智邦', 'Accton'),
    'Advantech Co Ltd': ('2395', '研華', 'Advantech'),
    'Orient Semiconductor Electronics Ltd': ('2329', '華泰', 'OSE'),
    'International Semiconductor Technology Ltd': ('3520', '振曜', 'IST'),
    'Advanced Wireless Semiconductor Co': ('5765', '穩懋', 'AWS'),
    'CHC Healthcare Group': ('4164', '承業', 'CHC'),
    'Sanyo Electric Taiwan Co Ltd': ('5765', '台灣三洋', 'Sanyo TW'),
    'Taiwan Sanyo Electric Co Ltd': ('5765', '台灣三洋', 'Sanyo TW'),
    'Dynamic Holding Co Ltd': ('5765', '力鼎', 'Dynamic'),
    'Dynamic Electronics Co Ltd': ('5765', '力鼎', 'Dynamic'),
    'Sunshine Asset Management Co Ltd': ('5765', '尚立', 'Sunshine'),
    'Speed Tech Corp': ('5765', '立德', 'Speed Tech'),
    'JPP Holding Co Ltd': ('5765', 'JPP', 'JPP'),
    'Egis Technology Inc': ('6462', '神盾', 'Egis'),
    'Creative Sensor Inc': ('5765', '創意', 'Creative Sensor'),
    'Alcor Micro Corp/Taiwan': ('5765', '宏觀', 'Alcor Micro'),
    'Ultra Chip Inc': ('5765', '笙泉', 'Ultra Chip'),
    'Sonix Technology Co Ltd': ('5765', '松翰', 'Sonix'),
    'Weltrend Semiconductor': ('5765', '偉詮電', 'Weltrend'),
    'C-Media Electronics Inc': ('5765', '驊訊', 'C-Media'),
    'Microelectronics Technology': ('5765', '全訊', 'MET'),
    'Microelectronics Technology Inc': ('5765', '全訊', 'MET'),
    'Anpec Electronics Corp': ('5765', '茂達', 'Anpec'),
    'UPI Semiconductor Corp': ('5765', '力智', 'UPI'),
    'Sitronix Technology Corp': ('5765', '矽創', 'Sitronix'),
    'FocalTech Systems Co Ltd': ('5765', '敦泰', 'FocalTech'),
    'Raydium Semiconductor Corp': ('5765', '奇景', 'Raydium'),
    'Amazing Microelectronic Corp': ('5765', '偉詮', 'Amazing'),
    'Fitipower Integrated Technology Inc': ('5765', '天鈺', 'Fitipower'),
    'Pan Jit International Inc': ('5765', '強茂', 'Pan Jit'),
    'Tyntek Corp': ('5765', '鼎元', 'Tyntek'),
    'Sigurd Microelectronics Corp': ('5765', '矽格', 'Sigurd'),
    'Nuvoton Technology Corp': ('4919', '新唐', 'Nuvoton'),
    'SensorTek Technology Corp': ('5765', '矽創', 'SensorTek'),
    'Sensortek Technology Corp': ('5765', '矽創', 'SensorTek'),
    'VIA Labs Inc': ('5765', '威鋒', 'VIA Labs'),
    'RichWave Technology Corp': ('5765', '立積', 'RichWave'),
    'Airoha Technology Corp': ('3032', '偉詮電', 'Airoha'),
    'MPI Corp': ('5765', '微精密', 'MPI'),
    'HERON NEUTRON MEDICAL CORP': ('5765', 'HERON', 'HERON'),
    'Advanced Energy Solution Holding Co Ltd': ('5765', '先進能源', 'AES'),
    'Chang Wah Electromaterials Inc': ('8070', '長華', 'Chang Wah'),
    'Chang Wah Technology Co Ltd': ('8070', '長華', 'Chang Wah'),
    'Nidec Chaun-Choung Technology Corp': ('5765', '全漢', 'Nidec CC'),
    'Chaun-Choung Technology Corp': ('5765', '全漢', 'CC Tech'),
    'Taiwan Paiho Ltd': ('9938', '百和', 'Paiho'),
    'SDI Corp': ('2351', '順德', 'SDI'),
    'Tong Hsing Electronic Industries Ltd': ('6271', '同欣電', 'Tong Hsing'),
    'Fu Sheng Industrial Co Ltd': ('6508', '惠光', 'Fu Sheng'),
    'Fusheng Precision Co Ltd': ('6508', '惠光', 'Fusheng'),
    'Askey Computer Co Ltd': ('5765', '亞旭', 'Askey'),
    'Askey Computer Corp': ('5765', '亞旭', 'Askey'),
    'Jess-Link Products Co Ltd': ('5765', '捷仕特', 'Jess-Link'),
    'Iron Force Industrial Co Ltd': ('5765', '鐵研', 'Iron Force'),
    'SYNNex Technology International Corp': ('2347', '聯強', 'Synnex'),
    'Andes Technology Corp': ('5765', '晶心科', 'Andes'),
    'Sinyi Realty Co': ('9940', '信義', 'Sinyi'),
    'Sinyi Realty Inc': ('9940', '信義', 'Sinyi'),
    'Taiwan Land Development Corp': ('2841', '台開', 'TLD'),
    'Delpha Construction Co Ltd': ('5765', '長虹', 'Delpha'),
    'Goldsun Building Materials Co Ltd': ('1805', '飛宏', 'Goldsun'),
    'Goldsun Development & Construction Co Ltd': ('5765', '金山', 'Goldsun Dev'),
    'Champion Building Materials Co Ltd': ('5765', '冠軍', 'Champion'),
    'Radium Life Tech Co Ltd': ('5765', '鐳昱', 'Radium'),
    'Ya Hsin Industrial Co Ltd': ('5765', '亞信', 'Ya Hsin'),
    'Jinan Acetate Chemical Co Ltd': ('5765', '濟南', 'Jinan'),
    'Ability Enterprise Co Ltd': ('5765', '精能', 'Ability'),
    'Ability Opto-Electronics Technology Co Ltd': ('5765', '精能光電', 'Ability Opto'),
    'AV TECH Corp': ('5765', '陞泰', 'AV Tech'),
    'AV Tech Corp': ('5765', '陞泰', 'AV Tech'),
    'AV Tech Corp/Taiwan': ('5765', '陞泰', 'AV Tech'),
    'Vivotek Inc': ('3454', '晶睿', 'VIVOTEK'),
    'Audix Corp': ('5765', '合勤控', 'Audix'),
    'Avision Inc': ('5765', '虹光', 'Avision'),
    'Chenbro Micom Co Ltd': ('8210', '勤誠', 'Chenbro'),
    'Arima Communication Corp': ('5765', '華冠', 'Arima Comm'),
    'Arima Communications Corp': ('5765', '華冠', 'Arima Comm'),
    'Arima Computer Corp': ('5765', '華宇', 'Arima'),
    'Ampak Technology Inc': ('5765', '正基', 'AMPAK'),
    'Inventec Appliances Corp': ('5765', '英華達', 'IAC'),
    'Ho Tung Chemical Corp': ('1714', '和桐', 'Ho Tung'),
    'Yosun Industrial Corp': ('5765', '友信', 'Yosun'),
    'Zeng Hsing Industrial Co Ltd': ('6192', '巨路', 'Zeng Hsing'),
    'Lai Yih Footwear Co Ltd': ('5765', '來益', 'Lai Yih'),
    'AP Memory Technology Corp': ('5765', 'AP', 'AP Memory'),
    'VisEra Technologies Co Ltd': ('5765', '采鈺', 'VisEra'),
    'Bafang Yunji International Co Ltd': ('5765', '八方雲集', 'Bafang'),
    'Gourmet Master Co Ltd': ('5765', '85度C', 'Gourmet Master'),
    'Wowprime Corp': ('5765', '王品', 'Wowprime'),
    'Ginko International Co Ltd': ('5765', '杏一', 'Ginko'),
    'Great Tree Pharmacy Co Ltd': ('5765', '大樹', 'Great Tree'),
    'Lung Yen Life Service Corp': ('5765', '龍巖', 'Lung Yen'),
    'Poya Co Ltd': ('5765', '寶雅', 'Poya'),
    'Poya International Co Ltd': ('5904', '寶雅', 'Poya'),
    'Test Rite International Co Ltd': ('2908', '特力', 'Test Rite'),
    'Test-Rite International Co': ('2908', '特力', 'Test Rite'),
    'Test-Rite International Co Ltd': ('2908', '特力', 'Test Rite'),
    'Tsann Kuen Enterprise Co Ltd': ('2430', '燦坤', 'Tsann Kuen'),
    'Mercuries & Associates Holding Ltd': ('2905', '三商', 'Mercuries'),
    'Mercuries & Associates Ltd': ('2905', '三商', 'Mercuries'),
    'Mercuries Life Insurance Co Ltd': ('2905', '三商', 'Mercuries'),
    'International CSRC Investment Holdings Co': ('5765', '國際中橡', 'CSRC'),
    'Xinwei Communications Holdings Ltd': ('5765', '信威', 'Xinwei'),
    'Yungtay Engineering Co Ltd': ('1507', '永大', 'Yungtay'),
    'Yung Chi Paint & Varnish Manufacturing Co Ltd': ('5765', '永記', 'Yung Chi'),
    'Yung Shin Pharmaceutical Industrial Co Ltd': ('5765', '永信', 'Yung Shin'),
    'YungShin Global Holding Corp': ('5765', '永信', 'YungShin'),
    'Yungshin Construction & Development Co Ltd': ('5765', '永信建設', 'Yungshin Const'),
    'Yuan High-Tech Development Co Ltd': ('5765', '宏遠', 'Yuan'),
    'Xxentria Technology Materials Corp': ('5765', '先進光', 'Xxentria'),
    'Cenra Inc': ('5765', '僑力', 'Cenra'),
    'Unizyx Holding Corp': ('5765', '合勤控', 'Unizyx'),
    'Zyxel Communications Corp': ('2391', '合勤', 'ZyXEL'),
    'Zyxel Group Corp': ('5765', '合勤控', 'Zyxel Group'),
    'LES Enphants Co Ltd': ('5765', '麗嬰房', 'LES'),
    'AcBel Polytech Inc': ('6282', '康舒', 'AcBel'),
    'Savior Lifetec Corp': ('5765', '崇越', 'Savior'),
    'Actron Technology Corp': ('5765', '亞弘電', 'Actron'),
    'Brightled Electronics Corp': ('5765', '億光', 'Bright LED'),
    'Apex International Co Ltd': ('4927', '泰鼎', 'Apex'),
    'ACES Electronic Co Ltd': ('5765', '雅新', 'ACES'),
    'GigaMedia Ltd': ('5765', '和信', 'GigaMedia'),
    'Jenn Feng Industrial Co Ltd': ('5765', '震鋒', 'Jenn Feng'),
    'Jenn Feng New Energy Co Ltd': ('5765', '震鋒', 'Jenn Feng'),
    'Kaimei Electronic Corp': ('5765', '凱美', 'Kaimei'),
    'Taiwan Kai Yih Industrial Co Ltd': ('5765', '台灣開益', 'Kai Yih'),
    'Advancetek Enterprise Co Ltd': ('5765', '先進光', 'Advancetek'),
    'Everskill Technology Co Ltd': ('5765', '勤凱', 'Everskill'),
    'Zig Sheng Industrial Co Ltd': ('5765', '集盛', 'Zig Sheng'),
    'ZIG Sheng IND Co Ltd': ('5765', '集盛', 'Zig Sheng'),
    'Nan Liu Enterprise Co Ltd': ('1752', '南六', 'Nan Liu'),
    'Nan Pao Resins Chemical Co Ltd': ('4766', '南寶', 'Nan Pao'),
    'Nantex Industry Co Ltd': ('5765', '南帝', 'Nantex'),
    'Namchow Chemical Industrial Co Ltd': ('5765', '南僑', 'Namchow'),
    'Namchow Chemical Industrial Ltd': ('5765', '南僑', 'Namchow'),
    'Namchow Holdings Co Ltd': ('5765', '南僑', 'Namchow'),
    'Gallant Micro Machining Co Ltd': ('2236', '百微', 'Gallant'),
    'Gallant Precision Machining Co Ltd': ('2236', '百微', 'Gallant'),
    'Jentech Precision Industrial Co Ltd': ('5765', '建準', 'Jentech'),
    'Sunonwealth Electric Machine Industry Co Ltd': ('5765', '建準', 'Sunonwealth'),
    'Rechi Precision Co Ltd': ('5765', '瑞智', 'Rechi'),
    'Tong-Tai Machine & Tool Co Ltd': ('5765', '東台', 'Tong-Tai'),
    'XAC Automation Corp': ('5765', '百德', 'XAC'),
    'Hiwin Technologies Corp': ('2049', '上銀', 'Hiwin'),
    'Hiwin Mikrosystem Corp': ('5765', '大銀微系統', 'Hiwin Mikro'),
    'Apex Dynamics Inc': ('5765', '精銳', 'Apex Dynamics'),
    'Goodway Machine Corp': ('5765', '程泰', 'Goodway'),
    'Kaulin Manufacturing Co Ltd': ('5765', '高林', 'Kaulin'),
    'Rexon Industrial Corp Ltd': ('5765', '力山', 'Rexon'),
    'All Ring Tech Co Ltd': ('5765', '均豪', 'All Ring'),
    'Ichia Technologies Inc': ('5765', '伊建', 'Ichia'),
    'Infortrend Technology Inc': ('2495', '普安', 'Infortrend'),
    'Posiflex Technology Inc': ('5765', '振樺電', 'Posiflex'),
    'Stark Technology Inc': ('5765', '朋程', 'Stark'),
    'MIN AIK Technology Co Ltd': ('5765', '敏鈞', 'MIN AIK'),
    'Cenra Inc': ('5765', '僑力', 'Cenra'),
    'Shining Building Business Co Ltd': ('5765', '欣陸', 'Shining'),
    'Shinfox Energy Co Ltd': ('5765', '信邦', 'Shinfox'),
    'Shin Foong Specialty & Applied Materials Co Ltd': ('5765', '信豐', 'Shin Foong'),
    'Li Cheng Enterprise Co Ltd': ('5765', '力成', 'Li Cheng'),
    'Meiloon Industrial Co': ('5765', '美隆', 'Meiloon'),
    'Swancor Holding Co Ltd': ('5765', '上緯', 'Swancor'),
    'Newmax Technology Co Ltd': ('5765', '新復興', 'Newmax'),
    'Nichidenbo Corp': ('5765', '立隆電', 'Nichidenbo'),
    'Global PMX Co Ltd': ('5765', '全球', 'Global PMX'),
    'Lian HWA Food Corp': ('1231', '聯華食', 'Lian Hwa'),
    'Tainan Enterprises Co Ltd': ('1473', '台南', 'Tainan'),
    'Tainan Spinning Co Ltd': ('1440', '南紡', 'Tainan Spinning'),
    'Ho Tung Chemical Corp': ('1714', '和桐', 'Ho Tung'),
    'Taiflex Scientific Co Ltd': ('5765', '台虹', 'Taiflex'),
    'TaiDoc Technology Corp': ('5765', '泰博', 'TaiDoc'),
    'Taigen Biopharmaceuticals Holdings Ltd': ('5765', '太景', 'Taigen'),
    'Taiwan FU Hsing Industrial Co Ltd': ('5765', '台灣福興', 'Fu Hsing'),
    'Taiwan Hon Chuan Enterprise Co Ltd': ('5765', '台灣宏全', 'Hon Chuan'),
    'Merry Electronics Co Ltd': ('2439', '美律', 'Merry'),
    'Lotes Co Ltd': ('3533', '嘉澤', 'Lotes'),
    'Sinbon Electronics Co Ltd': ('3023', '信邦', 'Sinbon'),
    'Wistron NeWeb Corp': ('5765', '啟碁', 'WNC'),
    'WNC Corp /Taiwan': ('5765', '啟碁', 'WNC'),
    'Sunrex Technology Corp': ('5765', '旭德', 'Sunrex'),
    'Taiwan Surface Mounting Technology Co Ltd': ('5765', '台表科', 'TSMT'),
    'Taiwan Surface Mounting Technology Corp': ('5765', '台表科', 'TSMT'),
    'Transcom Inc/Taiwan': ('5765', '統懋', 'Transcom'),
    'TA-I Technology Co Ltd': ('5765', '鼎基', 'TA-I'),
    'O-TA Precision Industry Co Ltd': ('5765', '歐達', 'O-TA'),
    'KMC Kuei Meng International Inc': ('5765', '桂盟', 'KMC'),
    'Spirox Corp': ('5765', '昇貿', 'Spirox'),
    'Elite Advanced Laser Corp': ('5765', '創鑫', 'Elite Laser'),
    'San Shing Fastech Corp': ('5765', '三星', 'San Shing'),
    'Gudeng Precision Industrial Co Ltd': ('5765', '家登', 'Gudeng'),
    'Machvision Inc': ('5765', '由田', 'Machvision'),
    'Syncmold Enterprise Corp': ('5765', '信昌電', 'Syncmold'),
    'Optimax Technology Corp': ('5765', '達運', 'Optimax'),
    'Pegavision Corp': ('5765', '晶碩', 'Pegavision'),
    'St Shine Optical Co Ltd': ('1565', '明基材', 'St Shine'),
    'Topkey Corp': ('5765', '鼎基', 'Topkey'),
    'General Interface Solution GIS Holding Ltd': ('5765', 'GIS', 'GIS'),
    'General Interface Solution Holding Ltd': ('5765', 'GIS', 'GIS'),
    'Acbel Polytech Inc': ('6282', '康舒', 'AcBel'),
    'Darwin Precisions Corp': ('5765', '大億', 'Darwin'),
    'Phihong Technology Co Ltd': ('5765', '飛宏', 'Phihong'),
    'Entire Technology Co Ltd': ('5765', '全台', 'Entire'),
    'ShunSin Technology Holding Ltd': ('5765', '順信', 'ShunSin'),
    'Bizlink Holding Inc': ('5765', '貿聯', 'BizLink'),
    'Silitech Technology Corp': ('5765', '松翰', 'Silitech'),
    'Airtac International Group': ('1590', '亞德客-KY', 'AirTAC'),
    'T JOIN Transportation Co': ('5765', 'T JOIN', 'T JOIN'),
    'Chlitina Holding Ltd': ('5765', '克麗緹娜', 'Chlitina'),
    'Cenra Inc': ('5765', '僑力', 'Cenra'),
    'Kinik Co': ('5765', '中砂', 'Kinik'),
    'Kinko Optical Co Ltd': ('5765', '建鈺', 'Kinko'),
    'Kung Long Batteries Industrial Co Ltd': ('5765', '廣隆', 'Kung Long'),
    'Simplo Technology Co Ltd': ('6121', '新普', 'Simplo'),
    'Dyaco International Inc': ('5765', '岱宇', 'Dyaco'),
    'Yeong Guan Energy Technology Group Co Ltd': ('5765', '永冠', 'Yeong Guan'),
    'Yeun Chyang Industrial Co Ltd': ('5765', '源鼎', 'Yeun Chyang'),
    'Chin-Poon Industrial Co': ('2355', '敬鵬', 'Chin-Poon'),
    'Chin-Poon Industrial Co Ltd': ('2355', '敬鵬', 'Chin-Poon'),
    'Lotuspharm Co Ltd': ('5765', '荷蘭藥', 'Lotuspharm'),
    'Lotus Pharmaceutical Co Ltd': ('5765', '蓮花藥', 'Lotus'),
    '91APP Inc': ('6741', '91APP*-KY', '91APP'),
    'Brightled Electronics Corp': ('5765', '億光', 'Bright LED'),
    'Browave Corp': ('5765', '波若威', 'Browave'),
    'EZconn Corp': ('5765', '以勤', 'EZconn'),
    'Brogent Technologies Inc': ('5765', '智崴', 'Brogent'),
    'Hon Precision Inc': ('5765', '鴻準', 'Hon Precision'),
    'Foxsemicon Integrated Technology Inc': ('5765', '鴻準', 'Foxsemicon'),
    'TON YI Industrial Corp': ('5765', '統一實', 'Ton Yi'),
    'Ton Yi Industrial Corp': ('9907', '統一實', 'Ton Yi'),
    'TYC Brother Industrial Co Ltd': ('1319', '東陽', 'TYC'),
    'Formosan Rubber Group Inc': ('2105', '正新', 'FRG'),
    'Brighton-Best International Taiwan Inc': ('5765', '恒耀', 'Brighton-Best'),
    'SilverStone Technology Co Ltd': ('5765', '銀欣', 'SilverStone'),
    'Systemex Inc': ('5765', '精誠', 'Systemex'),
    'Scientech Corp': ('5765', '崇越', 'Scientech'),
    'Corpro Technology Co Ltd': ('5765', '核心', 'Corpro'),
    'Phoenix Silicon International Corp': ('5765', '鳳凰光', 'PSI'),
    'Phoenix Precision Technology Corp': ('5765', '鳳凰光', 'PPT'),
    'AlliedSig Inc': ('5765', '聯合訊號', 'AlliedSig'),
    'Spirox Corp': ('5765', '昇貿', 'Spirox'),
    'Unitech Printed Circuit Board Corp': ('5765', '聯茂', 'Unitech'),
    'Universal Microwave Technology Inc': ('5765', '穩茂', 'UMT'),
    'Universal Vision Biotechnology Co Ltd': ('3594', '磐石', 'UVB'),
    'Corning Display Technologies Co Ltd': ('5765', '康寧', 'Corning'),
    'Concraft Holding Co Ltd': ('5765', '嘉晶', 'Concraft'),
    'Grand Hall Enterprise Co Ltd': ('5765', '明堂', 'Grand Hall'),
    'Lotes Co Ltd': ('3533', '嘉澤', 'Lotes'),
    'Ichia Technologies Inc': ('5765', '伊建', 'Ichia'),
    'FLEXium Interconnect Inc': ('6269', '台郡', 'Flexium'),
    'JPP Holding Co Ltd': ('5765', 'JPP', 'JPP'),
    'JPC connectivity Inc': ('5765', 'JPC', 'JPC'),
    'Ko Ja (Cayman) Co Ltd': ('5765', '高佳', 'Ko Ja'),
    'Kerry TJ Logistics Co Ltd': ('2608', '嘉里大榮', 'Kerry TJ'),
    'Kaori Heat Treatment Co Ltd': ('5765', '高力', 'Kaori'),
    'Newmax Technology Co Ltd': ('5765', '新復興', 'Newmax'),
    'Universal Scientific Industrial Co Ltd': ('6145', '日月光投控', 'USI'),
    'Taiwan FU Hsing Industrial Co Ltd': ('5765', '台灣福興', 'Fu Hsing'),
    'Formosan Rubber Group Inc': ('2105', '正新', 'FRG'),
    'EirGenix Inc': ('6589', '台康生技', 'EirGenix'),
    'Siliconware Precision Industries Co Ltd': ('2325', '矽品', 'SPIL'),
    'Siliconware Precision Industries Co': ('2325', '矽品', 'SPIL'),
    'Century Wind Power Co Ltd': ('5765', '世紀風電', 'Century Wind'),
    'Starlux Airlines Co Ltd': ('2646', '星宇航空', 'STARLUX'),
    'Tigerair Taiwan Co Ltd': ('6757', '台灣虎航', 'Tigerair'),
}

# Apply manual mapping
for name in list(no_ticker) + [n for n, _ in ticker_not_found]:
    if name in MANUAL_MAP and name not in mapping:
        code, short_name, eng = MANUAL_MAP[name]
        mapping[name] = {
            'code': code,
            'short_name': short_name,
            'eng_abbrev': eng,
            'full_name': '',
            'match_method': 'manual',
        }

# Recalculate unmatched
still_unmatched = [n for n in all_names if n not in mapping]
print(f"\nAfter manual mapping:")
print(f"  Total matched: {len(mapping)}")
print(f"  Still unmatched: {len(still_unmatched)}")
if still_unmatched:
    print("\nStill unmatched:")
    for n in still_unmatched:
        tickers = company_tickers[n]
        print(f"  {n}  tickers={tickers}")

# ── Write final mapping CSV ──
with open('/home/tearicee/data_collector/nbim/nbim_tw_mapping.csv', 'w', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerow(['nbim_name', 'stock_code', 'chinese_short_name', 'eng_abbrev', 'match_method'])
    for name in sorted(mapping.keys()):
        m = mapping[name]
        writer.writerow([name, m['code'], m['short_name'], m['eng_abbrev'], m['match_method']])

print(f"\nFinal mapping saved to nbim_tw_mapping.csv ({len(mapping)} entries)")
